#!/bin/sh
# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh
runApplication -o changeDictionary
runApplication -o offbeat
#
runApplication -o postProcess -func sampleDict

outerRadialStressSimulation=$(cat postProcessing/sampleDict/10/outer/symmTensorField/sigma | sed -E 's/.*\(([^\s]+).*/\1/' | cut -d' ' -f1)
outerDispSimulation=$(cat postProcessing/sampleDict/10/outer/vectorField/D | sed -E 's/.*\(([^\s]+).*/\1/' | cut -d' ' -f1)
centerTempSimulation=$(cat postProcessing/probes/0/T |tail -n 1| awk '{print $NF}')

outerRadialStressExpected=-100e6
outerDispExpected=-0.8e-6
centerTempExpected=459.66666667
#


echo "outer radial stress: $outerRadialStressSimulation" >> results
echo "Expected value: $outerRadialStressExpected" >> results
echo "outer displacement: $outerDispSimulation" >> results
echo "Expected value: $outerDispExpected" >> results
echo "center temperature: $centerTempSimulation" >> results
echo "Expected value: $centerTempExpected" >> results


relErrorOuterRadialStress=`echo - | awk '{print 100*(var1-var2)/var2}' \
var1="$outerRadialStressSimulation" var2="$outerRadialStressExpected"`
relErrorOuterDisp=`echo - | awk '{print 100*(var1-var2)/var2}' \
var1="$outerDispSimulation" var2="$outerDispExpected"`
relErrorCenterTemp=`echo - | awk '{print 100*(var1-var2)/var2}' \
var1="$centerTempSimulation" var2="$centerTempExpected"`





echo "Relative error for outer radial stress: $relErrorOuterRadialStress%" >> results
echo "Relative error for outer displacement: $relErrorOuterDisp%" >> results
echo "Relative error for center temperature: $relErrorCenterTemp%" >> results
