#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh
runApplication -o changeDictionary 
runApplication -o offbeat

oxideSimulation=$(tail -n1 postProcessing/probes/0/oxideThickness | awk '{print $2}')

oxideExptected=3.09346e-05

echo "Oxide thickness value: $oxideSimulation" >> results
echo "Expected oxide thickness: $oxideExptected" >> results

relError=$(awk -v var1="$oxideSimulation" \
               -v var2="$oxideExptected" \
               'BEGIN {print (100*(var1-var2)/var2)}')

echo "Relative error: $relError%" >> results
