#!/bin/sh
#----------------------------------------------------------------------------#
#       ______          _   __           ______                              #
#      / ____/  ___    / | / /          / ____/  ____   ____ _   ____ ___    #
#     / / __   / _ \  /  |/ /  ______  / /_     / __ \ / __ `/  / __ `__ \   #
#    / /_/ /  /  __/ / /|  /  /_____/ / __/    / /_/ // /_/ /  / / / / / /   #
#    \____/   \___/ /_/ |_/          /_/       \____/ \__,_/  /_/ /_/ /_/    #
#    Copyright (C) 2015 - 2022 EPFL                                          #
#----------------------------------------------------------------------------#

cd ${0%/*} || exit 1    # Run from this directory

#==============================================================================*

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#==============================================================================*

isTest=$1


# Steady-state with the external neutron source
rm -rf steadyState
cp -r rootCase steadyState

if [ $isTest -eq 1 ]
then
    foamDictionary steadyState/0/neutroRegion/defaultExternalSourceFlux  -entry boundaryField.walls.type -set zeroGradient
    foamDictionary steadyState/0/neutroRegion/defaultFlux  -entry boundaryField.walls.type -set zeroGradient
    foamDictionary steadyState/0/neutroRegion/defaultFlux2 -entry boundaryField.walls.type -set zeroGradient
fi

GeN-Foam -case steadyState |
    tee steadyState/log.GeN-Foam |
    grep -E "Time =|deltaT|power:|keff"


#==============================================================================*
