#!/bin/bash

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh 

rm -f *.out

for case in  "Baker-Just" "Cathcart-Pawel-Prater-Courtright" "Leistikov-Prater-Courtright"
do
    foamListTimes -rm
    rm -rf postProcessing
    
    sed -i "s/oxidationKineticsModel .*;/oxidationKineticsModel MATPRO-CORROS-PWR|$case;/gm" constant/solverDict;
    runApplication -o offbeat
    
    cp -f postProcessing/oxideThickness/0/oxideThickness $case.out
done

python test.py
