#==============================================================================*
#
# GeN-Foam GitLab CI/CD
#
# Prepared by:
#     Carlo Fiorina <carlo.fiorina@outlook.com; carlo.fiorina@epfl.ch;>, EPFL (Switzerland)
#     Thomas Guilbaud <thomas.guilbaud@epfl.ch>, EPFL/Transmutex SA (Switzerland)
#
# Comment: fix problem with build environment for test cases
#==============================================================================*

#image: ubuntu # opencfd/openfoam-dev
image: ubuntu

#==============================================================================*
#                                    Deploy
#==============================================================================*

pages:
  stage: deploy
  image: python:3.10.12
  allow_failure: true

  script:
    # Install and build doxygen doc
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get -y install doxygen graphviz perl texlive-bibtex-extra texlive-latex-extra
    - cd documentation/doxygen/Doxygen && doxygen && cd ../../../

    # Install and build Sphinx doc
    - pip3 install -U sphinx sphinx-rtd-theme sphinx_intl myst-parser sphinx-mermaid
    - cd pythonapi && pip3 install -e . && cd ..
    - python3 documentation/sphinx/generate_cpp_docs.py
    - sphinx-build -b html documentation/sphinx public

    # Move Doxygen documentation to the public directory alongside Sphinx
    - mv Documentation/doxygen/Doxygen/html/ public/doxygen

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

#==============================================================================*
