#==============================================================================*
#
# GeN-Foam GitLab CI/CD
#
# Prepared by:
#     Carlo Fiorina <carlo.fiorina@outlook.com; carlo.fiorina@epfl.ch;>, EPFL (Switzerland)
#     Thomas Guilbaud <thomas.guilbaud@epfl.ch>, EPFL/Transmutex SA (Switzerland)
#
# Comment: fix problem with build environment for test cases
#==============================================================================*

#image: ubuntu # opencfd/openfoam-dev
image: ubuntu

#stages:
#  - build
#  - test
#  - deploy

#cache:
#  key: $CI_COMMIT_REF_SLUG
#  paths:
#    - GeN-Foam/Make/
#    - GeN-Foam/classes/thermalHydraulics/*/lnInclude/
#    - GeN-Foam/classes/thermalHydraulics/*/Make

#artifacts:
#  paths:
#    - GeN-Foam/Make/
#    - GeN-Foam/classes/thermalHydraulics/*/lnInclude/
#    - GeN-Foam/classes/thermalHydraulics/*/Make

#before_script:
#  - export DEBIAN_FRONTEND=noninteractive
#  - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#  - cd GeN-Foam
#  - ./Allwclean; ./Allwmake

#==============================================================================*
#                                    Build
#==============================================================================*

#build-job:
#  stage: build
#  when: manual
#  script:
#    - pwd
#    - export DEBIAN_FRONTEND=noninteractive
#    #- apt-get update
#    #- apt-get -y install make cmake gcc g++ wget
#    #- wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | bash
#    #- apt-get -y install openfoam2206-default
#    #- chmod 775 /usr/lib/openfoam/openfoam2206/etc/bashrc
#    #- echo "source /usr/lib/openfoam/openfoam2206/etc/bashrc || true" >> ~/.bashrc
#    #- source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - export WM_PROJECT_USER_DIR="/builds/foam-for-nuclear/GeN-Foam"
#    #- pwd
#    #- which icoFoam
#    # - git clone https://gitlab.com/foam-for-nuclear/GeN-Foam.git
#    - cd GeN-Foam
#    - ./Allwclean; ./Allwmake
#    - cp -r /root/OpenFOAM/ ./
#  #timeout: 6h
#  artifacts:
#    paths:
#    #- ../../../usr/lib/openfoam
#    #- GeN-Foam/
#    #- ../../../root/OpenFOAM/
#    #- ../../../root/.bashrc
#      - GeN-Foam/Make/
#      - GeN-Foam/classes/thermalHydraulics/*/lnInclude/
#      - GeN-Foam/classes/thermalHydraulics/*/Make




#==============================================================================*
#                                    Tests
#==============================================================================*

# --- 1D Tutorials

#test-1D_boiling:
#  stage: test
#  script:
#    - cp -r OpenFOAM /root/
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/1D_boiling
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/1D_boiling/log.simulation
#      - Tutorials/1D_boiling/test.out

#test-1D_CHF-imposedPower:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/1D_CHF/imposedPower
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/1D_CHF/imposedPower/log.simulation
#      - Tutorials/1D_CHF/imposedPower/test.out

#test-1D_CHF-imposedTemperature:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/1D_CHF/imposedTemperature
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/1D_CHF/imposedTemperature/log.simulation
#      - Tutorials/1D_CHF/imposedTemperature/test.out

#test-1D_HX-onePhase:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/1D_HX/onePhase
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/1D_HX/onePhase/log.simulation
#      - Tutorials/1D_HX/onePhase/test.out

#test-1D_HX-twoPhase:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/1D_HX/twoPhase
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/1D_HX/twoPhase/log.simulation
#      - Tutorials/1D_HX/twoPhase/test.out

#test-1D_MSR_pointKinetics:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/1D_MSR_pointKinetics
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/1D_MSR_pointKinetics/log.simulation
#      - Tutorials/1D_MSR_pointKinetics/test.out

#test-1D_PSBT_SC:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/1D_PSBT_SC
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/1D_PSBT_SC/log.simulation
#      - Tutorials/1D_PSBT_SC/test.out


#------------------------------------------------------------------------------*
# --- 2D Tutorials

#test-2D_cavityBoussinesq:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/2D_cavityBoussinesq
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/2D_cavityBoussinesq/log.simulation
#      - Tutorials/2D_cavityBoussinesq/test.out

#test-2D_KNS37-L22:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/2D_KNS37-L22
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/2D_KNS37-L22/log.simulation
#      - Tutorials/2D_KNS37-L22/test.out

#test-2D_FFTF:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/2D_FFTF
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/2D_FFTF/log.simulation
#      - Tutorials/2D_FFTF/test.out

#test-2D_MSFR:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/2D_MSFR
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/2D_MSFR/log.simulation
#      - Tutorials/2D_MSFR/test.out

#test-2D_onePhaseAndPointKineticsCoupling:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/2D_onePhaseAndPointKineticsCoupling
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/2D_onePhaseAndPointKineticsCoupling/log.simulation
#      - Tutorials/2D_onePhaseAndPointKineticsCoupling/test.out

#test-2D_voidMotionNoPhaseChange:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/2D_voidMotionNoPhaseChange
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/2D_voidMotionNoPhaseChange/log.simulation
#      - Tutorials/2D_voidMotionNoPhaseChange/test.out


#------------------------------------------------------------------------------*
# --- 3D Tutorials

#test-3D_SmallESFR:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/3D_SmallESFR
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/3D_SmallESFR/log.simulation
#      - Tutorials/3D_SmallESFR/test.out


#------------------------------------------------------------------------------*
# --- SN-solver Tutorials

#test-Godiva_SN:
#  stage: test
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials/Godiva_SN
#    - ./Alltest
#  timeout: 6h
#  dependencies:
#    - build-job
#  artifacts:
#    paths:
#      - Tutorials/Godiva_SN/log.simulation
#      - Tutorials/Godiva_SN/test.out


#------------------------------------------------------------------------------*
# --- End concat all test.out

#test-merge-results:
#  stage: test
  # Need all the previous tests to be completed before running
#  needs: [
#    build-job,
#    test-1D_boiling,
#    test-1D_CHF-imposedPower,
#    test-1D_CHF-imposedTemperature,
#    test-1D_HX-onePhase,
#    test-1D_HX-twoPhase,
#    test-1D_MSR_pointKinetics,
#    test-1D_PSBT_SC,
#    test-2D_cavityBoussinesq,
#    test-2D_KNS37-L22,
#    test-2D_FFTF,
#    test-2D_MSFR,
#    test-2D_onePhaseAndPointKineticsCoupling,
#    test-2D_voidMotionNoPhaseChange,
#    test-3D_SmallESFR,
#    test-Godiva_SN
#  ]
#  script:
#    - source ~/.bashrc || true
#    - source /usr/lib/openfoam/openfoam2206/etc/bashrc || true
#    - cd Tutorials
#    - ./concatAllTests
#  dependencies:
#    - build-job
#    - test-1D_boiling
#    - test-1D_CHF-imposedPower
#    - test-1D_CHF-imposedTemperature
#    - test-1D_HX-onePhase
#    - test-1D_HX-twoPhase
#    - test-1D_MSR_pointKinetics
#    - test-1D_PSBT_SC
#    - test-2D_cavityBoussinesq
#    - test-2D_KNS37-L22
#    - test-2D_FFTF
#    - test-2D_MSFR
#    - test-2D_onePhaseAndPointKineticsCoupling
#    - test-2D_voidMotionNoPhaseChange
#    - test-3D_SmallESFR
#    - test-Godiva_SN
#  artifacts:
#    paths:
#      - Tutorials/regressionResults
#  allow_failure: true


#==============================================================================*
#                                    Deploy
#==============================================================================*

pages:
  stage: deploy
  image: python:latest

  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get -y install doxygen graphviz perl texlive-bibtex-extra texlive-latex-extra
    - cd Documentation/doxygen/Doxygen && doxygen && cd ../../../

    # Install MkDocs and any MkDocs plugins you use
    - pip install mkdocs mkdocs-material mkdocs-bibtex mkdocs-get-deps mkdocs-macros-plugin mkdocs-material-extensions

    # Move into the mkdocs folder to match the local setup
    - cd Documentation/mkdocs

    # Build the MkDocs documentation
    - python3 generate_docs.py
    - mkdocs build --site-dir ../../public
    - cd ../../

    # Move Doxygen documentation to the public directory alongside MkDocs
    - mv Documentation/doxygen/Doxygen/html/ public/doxygen

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

#==============================================================================*
