#==============================================================================*
#
# GeN-Foam GitLab CI/CD
#
# Prepared by:
#     Carlo Fiorina <carlo.fiorina@outlook.com; carlo.fiorina@epfl.ch;>, EPFL (Switzerland)
#     Thomas Guilbaud <thomas.guilbaud@epfl.ch>, EPFL/Transmutex SA (Switzerland)
#
# Comment: fix problem with build environment for test cases
#==============================================================================*

#image: ubuntu # opencfd/openfoam-dev
image: ubuntu

#==============================================================================*
#                                    Deploy
#==============================================================================*

pages:
  stage: deploy
  image: python:latest

  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get -y install doxygen graphviz perl texlive-bibtex-extra texlive-latex-extra
    - cd Documentation/doxygen/Doxygen && doxygen && cd ../../../

    # Install MkDocs and any MkDocs plugins you use
    - pip install mkdocs mkdocs-material mkdocs-bibtex mkdocs-get-deps mkdocs-macros-plugin mkdocs-material-extensions

    # Move into the mkdocs folder to match the local setup
    - cd Documentation/mkdocs

    # Build the MkDocs documentation
    - python3 generate_docs.py
    - mkdocs build --site-dir ../../public
    - cd ../../

    # Move Doxygen documentation to the public directory alongside MkDocs
    - mv Documentation/doxygen/Doxygen/html/ public/doxygen

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

#==============================================================================*
