#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# clean OFFBEAT libs
wclean libso ./src/offbeat/src/SCIANTIX
wclean libso ./src/offbeat/src/offbeatLib

# clean src libs
wclean libso ./src/interpolationModels 
wclean libso ./src/solutionControl 
wclean libso ./src/profiles 
wclean libso ./src/crossSections
wclean libso ./src/porousMediaModels
wclean libso ./src/thermophysicalProperties
wclean libso ./src/multiRegion
wclean libso ./src/fvPatchFields

# clean modules
wclean libso ./applications/modules/thermalHydraulics
wclean libso ./applications/modules/neutronics
wclean libso ./applications/modules/thermoMechanics
wclean libso ./applications/modules/fuelBehaviour
wclean libso ./applications/modules/openFoamImported

# clean apps
wclean ./applications/solvers/GeN-Foam

# clean tools 
wclean ./tests/hydrogenThermophysicalProperties
wclean ./tests/radialBasisFunctions

