#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso ./src/classes/common
wclean libso ./src/classes/multiRegion
wclean libso ./src/classes/thermalHydraulics/src
wclean libso ./src/classes/thermalHydraulics/solvers
wclean libso ./src/classes/neutronics
wclean libso ./src/classes/thermoMechanics

if [ -d "./src/classes/offbeat/src/offbeatLib" ]
then
    wclean libso ./src/classes/offbeat/solvers
    wclean libso ./src/classes/offbeat/src/offbeatLib
    wclean libso ./src/classes/offbeat/src/SCIANTIX
fi

wclean libso ./src/classes/openFoamImportedSolvers
wclean ./GeN-Foam

wclean ./tests/hydrogenThermophysicalProperties
wclean ./tests/radialBasisFunctions
