#!/bin/bash
#==============================================================================*

cd ${0%/*} || exit 1    # Run from this directory

clear

#==============================================================================*

# Function to display help
usage() {
    echo "Usage: $0 [-j N|--jobs N] [--fmi] [--help]"
    exit 1
}

# Default values
num_jobs=1
fmi_flag=false

# Parse options using getopt
PARSED_OPTIONS=$(getopt -n "$0" -o j:h --long jobs:,fmi,help -- "$@")
if [ $? -ne 0 ]; then
    usage
fi

# Rearrange the positional parameters based on the parsed options
eval set -- "$PARSED_OPTIONS"

# Process the options
while true; do
    case "$1" in
        -j | --jobs)
            num_jobs="$2"
            shift 2
            ;;
        --fmi)
            fmi_flag=true
            shift
            ;;
        --help)
            usage
            ;;
        --)
            shift
            break
            ;;
        *)
            usage
            ;;
    esac
done

# Script logic
echo "Number of jobs: $num_jobs"
echo "FMI flag: $fmi_flag"

# Collect all submodules
git submodule update --init --recursive

# Build with FMI option
if [ $fmi_flag = 'true' ]
then

    cd thirdParty/FMU4FOAM

    # Build paths
    pathLibFMU4FOAM=$(pwd)
    pathLibECI4FOAM=$pathLibFMU4FOAM/ECI4FOAM

    # LIB_ECI4FOAM not found -> build and add env var
    if [[ -z "$LIB_ECI4FOAM" ]] || [ $pathLibECI4FOAM != $LIB_ECI4FOAM ]
    then
        echo "Build ECI4FOAM"
        ./build-ECI4FOAM.sh -j$num_jobs
    fi

    # Force export of LIB path
    export LIB_ECI4FOAM=$pathLibECI4FOAM

    # Build FMU4FOAM only if found LIB_ECI4FOAM env var
    if [[ ! -z "$LIB_ECI4FOAM" ]]
    then
        # LIB_FMU4FOAM not found -> build and add env var
        if [[ -z "$LIB_FMU4FOAM" ]] || [ $pathLibFMU4FOAM != $LIB_FMU4FOAM ]
        then
            echo "Build FMU4FOAM"
            ./Allwmake -j$num_jobs
        fi

        # Force export of LIB path
        export LIB_FMU4FOAM=$pathLibFMU4FOAM
    fi

    cd ../..

    echo -e '\nIf you build ECI4FOAM or FMU4FOAM for FMI coupled simulation.'
    echo -e 'It is recommanded to add the following lines to your ~/.bashrc\n'
    echo -e "## ECI4FOAM\nexport LIB_ECI4FOAM=$pathLibECI4FOAM"
    echo -e "## FMU4FOAM\nexport LIB_FMU4FOAM=$pathLibFMU4FOAM\n"


else
    # Remove the environment variable only in this script, does not affect the
    # same variables in the .bashrc
    unset LIB_ECI4FOAM
    unset LIB_FMU4FOAM
fi

#==============================================================================*

echo "Allwmake GeN-Foam"

# Make OFFBEAT libs
wmake -j$num_jobs ./src/offbeat/src/SCIANTIX
wmake -j$num_jobs ./src/offbeat/src/offbeatLib

# Make src libs
wmake -j$num_jobs ./src/interpolationModels
wmake -j$num_jobs ./src/solutionControl
wmake -j$num_jobs ./src/profiles
wmake -j$num_jobs ./src/crossSections
wmake -j$num_jobs ./src/porousMediaModels
wmake -j$num_jobs ./src/thermophysicalProperties
wmake -j$num_jobs ./src/multiRegion
wmake -j$num_jobs ./src/functionObjects
wmake -j$num_jobs ./src/fvPatchFields

# Make modules
wmake -j$num_jobs ./applications/modules/thermalHydraulics
wmake -j$num_jobs ./applications/modules/neutronics
wmake -j$num_jobs ./applications/modules/thermoMechanics
wmake -j$num_jobs ./applications/modules/fuelBehaviour
wmake -j$num_jobs ./applications/modules/openFoamImported

# Make apps
wmake -j$num_jobs ./applications/solvers/GeN-Foam

echo -e "Make GeN-Foam completed\n"

#==============================================================================*

echo "Make tests"

wmake -j$num_jobs ./tests/hydrogenThermophysicalProperties
wmake -j$num_jobs ./tests/radialBasisFunctions

echo -e "Make tests completed\n"


#==============================================================================*
# Update the main README.md

current_version=$(grep -oP '(?<=based on OpenFOAM, ESI/OpenCFD distribution, currently )v\d+\d+\d+\d+' README.md)

current_version_num=$(echo $current_version | sed -r "s/v//")
new_version_num=$(echo $WM_PROJECT_VERSION | sed -r "s/v//")

checkUpgrade=$(echo "$current_version_num < $new_version_num" | bc -l)
if [[ $checkUpgrade -eq 1 ]]
then
    echo "Current OpenFOAM version ($current_version) is not the lastest."
    echo "Found OpenFOAM version $WM_PROJECT_VERSION, upgrade README.md"
    sed -i "s/$current_version/$WM_PROJECT_VERSION/" README.md
fi


#==============================================================================*
# Info

if [ $fmi_flag = 'true' ]
then
    echo -e '\nIf you build ECI4FOAM or FMU4FOAM for FMI coupled simulation.'
    echo -e 'It is recommanded to add the following lines to your ~/.bashrc\n'
    echo -e "## ECI4FOAM\nexport LIB_ECI4FOAM=$pathLibECI4FOAM"
    echo -e "## FMU4FOAM\nexport LIB_FMU4FOAM=$pathLibFMU4FOAM"
fi

#==============================================================================*
