#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

foamListTimes -rm
rm -fr postProcessing
rm -fr constant/polyMesh
rm -fr constant/referenceMesh
rm -f log.offbeat
rm -f *.png
rm -f relativeErrors
rm -f results
