#!/bin/bash
# 2022/01/06  Thomas Guilbaud, EPFL/Transmutex SA

# ---> Run from this directory
cd ${0%/*} || exit 1

# ---> Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#=============================================================================*
# Main parameters
#=============================================================================*

timeSteadyState=1000
timeTransient=1000


#=============================================================================*
# FMU Generation
#=============================================================================*

echo "Generate the secondary circuit FMU using Modelica"
cd rootCase/modelica
# Need to install ThermoPower package in OMEdit
# omc FMUGenSecCir.mos
# or export using OMEdit (need to copy paste the .fmu file in rootCase/modelica)
cd ../..


#=============================================================================*
# GeN-Foam Steady-state
#=============================================================================*

./Allrun_GeN-FoamStandalone


#=============================================================================*
# Steady-state
#=============================================================================*

# Run steady-state if it does not exist
if [ ! -d steadyState ]
then
    echo "GeN-Foam + FMUs steady-state simulation in critical mode"

    cp -r steadyStateStandalone steadyState
    cd steadyState

    if [ -d 0.converged ]
    then
        echo "Replace time folder 0 by 0.converged"
        rm -r 0
        cp -r 0.converged 0
    fi

    foamDictionary constant/neutroRegion/neutronicsProperties -entry eigenvalueNeutronics -set false
    foamDictionary constant/neutroRegion/neutronicsProperties -entry externalSourceNeutronics -set false
    foamDictionary constant/neutroRegion/externalSource -entry isExternalSource -set false
    cp constant/regionsDict_transient constant/regionsDict

    cp ../rootCase/system/controlDict system/
    cp ../rootCase/secondaryCircuit* .
    cp ../rootCase/modelica/*.fmu modelica/
    cp ../rootCase/simulink/*.fmu simulink/

    # Activate FMU Simulator function object
    sed -i "s|// #include \"FMUSimulatorFunction\"|#include \"FMUSimulatorFunction\"|" system/controlDict
    sed -i "s|// #include \"functions\"|#include \"functions\"|" system/controlDict

    # Set main parameter of the load follow simulation in FMU4FOAM object
    # sed -i "s/isLoadFollowReactivity = False/isLoadFollowReactivity = True/" secondaryCircuit*.py
    # sed -i "s/self.setVar(\"stepActivateExtReactivity.startTime\", 1000)/self.setVar(\"stepActivateExtReactivity.startTime\", 0)/" secondaryCircuit*.py

    foamDictionary system/controlDict -entry endTime -set $timeSteadyState
    foamDictionary system/controlDict -entry writeInterval -set $timeSteadyState
    foamDictionary system/controlDict -entry adjustTimeStep -set false
    foamDictionary system/controlDict -entry runTimeModifiable -set false

    GeN-Foam |
        tee log.GeN-Foam |
        grep -e "Time =\|deltaT\|Courant Number"

    cd ..
else
    echo "steadyState folder already exists, no steady-state simulation"
fi

#=============================================================================*
# Transient
#=============================================================================*

echo "Load follow transient simulation using reactivity control"

# Clean and prepare the case
rm -rf transientLoadFollowReactivity
cp -r steadyState transientLoadFollowReactivity
cp -r rootCase/system/* transientLoadFollowReactivity/system
cp rootCase/secondaryCircuit* transientLoadFollowReactivity
cp rootCase/modelica/*.fmu transientLoadFollowReactivity/modelica/
cp rootCase/simulink/*.fmu transientLoadFollowReactivity/simulink/
cd transientLoadFollowReactivity

# Activate FMU Simulator function object
sed -i "s|// #include \"FMUSimulatorFunction\"|#include \"FMUSimulatorFunction\"|" system/controlDict
sed -i "s|// #include \"functions\"|#include \"functions\"|" system/controlDict

# Set main parameter of the load follow simulation in FMU4FOAM object
# Can comment this line to see the effects of intrinsic feedback mechanism of
# the core
sed -i "s/isLoadFollowReactivity = False/isLoadFollowReactivity = True/" secondaryCircuit*.py

# Set simulation parameters
cp constant/regionsDict_transient constant/regionsDict
foamDictionary constant/neutroRegion/externalSource -entry isExternalSource -set false
foamDictionary system/controlDict -entry endTime -set $(($timeSteadyState + $timeTransient))
foamDictionary system/controlDict -entry writeInterval -set 100
foamDictionary system/controlDict -entry adjustTimeStep -set false
foamDictionary system/controlDict -entry runTimeModifiable -set false

# Simulation
GeN-Foam | tee log.GeN-Foam | grep -e "Time =\|deltaT\|Courant Number"

# Simulation with GeN-Foam in parallel
# decomposePar -allRegions
# mpirun -np 2 GeN-Foam -parallel | tee log.GeN-Foam | grep -E "Time =|deltaT|Courant Number"

cd ..

# =============================================================================*
