# AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
# Generated from OFFBEAT/OpenFOAM YAML docs + C++ TypeName/inheritance.

from __future__ import annotations
from typing import Any, ClassVar
from attrs import field
from foamForNuclear._attrs_tools import offbeat_define
from foamForNuclear.common import OffbeatDict

@offbeat_define
class ThermalSubSolver(OffbeatDict):
    """
    Base thermal solver class. It keeps the temperature field `T` unchanged from its
    initial configuration throughout the simulation.

    While the `constant` solver keeps the `T` field fixed by default, it is possible
    to alter the `T` field during the simulation by leveraging advanced OpenFOAM
    features like `#codeStream#`, `funkySetFields`, or specific function objects.

    At the moment, the `constant` class is one of two possible choices to couple
    OFFBEAT to an external solver that provides the `T` field directly at every
    time-step. At every coupled iteration, simply substitute the `T` file generated
    with the external solver in the starting time folder and (re)start the OFFBEAT
    simulation.


    Options
    -------
    heatFluxSummary : bool
        Activates the calculation of the heat flowing out from every surface of the
        domain and prints this information to the terminal.
        (default: False; required: False)

    calculateEnthalpy : bool
        Activates the calculation of the enthalpy deposited in the fuel materials
        (useful for RIA cases).
        (default: False; required: False)
    """
    TYPE: ClassVar[str] = 'constant'
    heatFluxSummary: bool = False
    calculateEnthalpy: bool = False

Constant = ThermalSubSolver  # alias

@offbeat_define
class ReadTemperature(Constant):
    """
    Thermal solver class that reads the temperature `T`  field from the time-step
    folders stored in a separate sub-folder (`constant/timeDependentInput/`).

    If the `T` file is present in the corresponding time folder for a given time
    step, the temperature field will be set accordingly. Otherwise, the `T` field
    remains constant.

    The `readTemperature` class provides a convenient way to explicitly couple
    OFFBEAT with an external solver that separately generates the `T` field.
    To use this class, simply place the `T` files generated by the external solver
    in the corresponding time folders within the
    `constant/timeDependentInput/` sub-folder.

    Options (inherited)
    -------------------
    heatFluxSummary : bool
        Activates the calculation of the heat flowing out from every surface of the
        domain and prints this information to the terminal.
        (default: False; required: False)

    calculateEnthalpy : bool
        Activates the calculation of the enthalpy deposited in the fuel materials
        (useful for RIA cases).
        (default: False; required: False)
    """
    TYPE: ClassVar[str] = 'readTemperature'

@offbeat_define
class SolidConduction(Constant):
    """
    Thermal solver class where the temperature distribution is obtained from
    the solution of the heat diffusion (energy conservation) equation.

    Options (inherited)
    -------------------
    heatFluxSummary : bool
        Activates the calculation of the heat flowing out from every surface of the
        domain and prints this information to the terminal.
        (default: False; required: False)

    calculateEnthalpy : bool
        Activates the calculation of the enthalpy deposited in the fuel materials
        (useful for RIA cases).
        (default: False; required: False)
    """
    TYPE: ClassVar[str] = 'solidConduction'
