#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory
set -o pipefail

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh

rm -f results
STATUS=0

runApplication -o foamDictionary constant/solverDict -entry mechanicsSolver -set $solver
runApplication -o foamListTimes -rm
rm -rf postProcessing

runApplication -o offbeat

python postprocess.py | tee -a results

#------------------------------------------------------------------------------
