#!/bin/sh
#----------------------------------------------------------------------------#
#       ______          _   __           ______                              #
#      / ____/  ___    / | / /          / ____/  ____   ____ _   ____ ___    #
#     / / __   / _ \  /  |/ /  ______  / /_     / __ \ / __ `/  / __ `__ \   #
#    / /_/ /  /  __/ / /|  /  /_____/ / __/    / /_/ // /_/ /  / / / / / /   #
#    \____/   \___/ /_/ |_/          /_/       \____/ \__,_/  /_/ /_/ /_/    #
#    Copyright (C) 2015 - 2022 EPFL                                          #
#----------------------------------------------------------------------------#

cd ${0%/*} || exit 1    # Run from this directory

#==============================================================================*

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# copy rootcase & set variables
rm -r thermoCase
cp -rf rootCase/ thermoCase/

foamDictionary thermoCase/system/controlDict -entry startTime -set 0
foamDictionary thermoCase/system/controlDict -entry maxCo -set 0.8
foamDictionary thermoCase/system/controlDict -entry endTime -set 0.1

decomposePar -allRegions -case thermoCase -copyUniform
mpirun -np 8 GeN-Foam -parallel -case thermoCase | tee log.GeN-Foam
reconstructPar -allRegions -case thermoCase
