#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

cases="
Case_ABWR/
Case_AP1000/
Case_BWR4/
Case_VVER440/
"

for case in $cases; do
    cd $case
    ./Allclean
    cd ..
done

rm -f results

#------------------------------------------------------------------------------
