#!/bin/bash
#----------------------------------------------------------------------------#
#       ______          _   __           ______                              #
#      / ____/  ___    / | / /          / ____/  ____   ____ _   ____ ___    #
#     / / __   / _ \  /  |/ /  ______  / /_     / __ \ / __ `/  / __ `__ \   #
#    / /_/ /  /  __/ / /|  /  /_____/ / __/    / /_/ // /_/ /  / / / / / /   #
#    \____/   \___/ /_/ |_/          /_/       \____/ \__,_/  /_/ /_/ /_/    #
#    Copyright (C) 2015 - 2022 EPFL                                          #
#----------------------------------------------------------------------------#

cd ${0%/*} || exit 1    # Run from this directory

#==============================================================================*

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#==============================================================================*

cases="steadyState transientRampSource"

# ---> Times
endTimeSteadyState=150
endTimeTransient=$(($endTimeSteadyState + 100))

setSteadyState() {
    cp -r $1 $2
    echo "Setting steady-state ..."
    foamDictionary $2/system/controlDict -entry endTime -set $endTimeSteadyState
    foamDictionary $2/system/controlDict -entry writeInterval -set $endTimeSteadyState
    cp dictionaries/steadyState/neutronicsProperties $2/constant/neutroRegion/neutronicsProperties
    cp dictionaries/steadyState/regionsDict $2/system/regionsDict
}

setTransient() {
    cp -r $1 $2
    echo "Setting $2 case..."
    cp dictionaries/transient/neutronicsProperties $2/constant/neutroRegion/neutronicsProperties
    foamDictionary $2/constant/neutroRegion/neutronicsProperties -entry eigenvalueNeutronics -set false
    foamDictionary $2/constant/neutroRegion/neutronicsProperties -entry externalSourceNeutronics -set true
    foamDictionary $2/constant/neutroRegion/externalSource \
        -entry externalSourceModulationTimeProfile.startTime -set $endTimeSteadyState
    foamDictionary $2/system/controlDict -entry endTime -set $endTimeTransient
    foamDictionary $2/system/controlDict -entry deltaT -set 1e-7
    foamDictionary $2/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $2/system/controlDict -entry writeInterval -set 10
    cp dictionaries/transient/regionsDict $2/system/regionsDict
    GeN-Foam -initializeMappedFields -case $2
}

#==============================================================================*

# ---> Simulation cases
for caseName in $cases; do
    # ---> Setup case
    case "$caseName" in
        "steadyState")
            setSteadyState rootCase $caseName
            ;;
        "transientRampSource")
            setTransient steadyState $caseName
            ;;
    esac

    # ---> Start gnuplot if it exist
    if command -v gnuplot &> /dev/null; then
        case "$caseName" in
            "steadyState")
                gnuplot -e "log='$caseName/log.GeN-Foam'" plottingTools/residuals - &> /dev/null &
                ;;
            "transientRampSource")
                # gnuplot -e "log='$caseName/log.GeN-Foam'" plottingTools/residualsAndPhysics - &> /dev/null &
                gnuplot -e "log='$caseName/log.GeN-Foam'" plottingTools/physicsParameters - &> /dev/null &
                # gnuplot -e "log='$caseName/log.GeN-Foam'" plottingTools/powerPlot.r - &> /dev/null &
                ;;
        esac
    else
        echo "gnuplot could not be found"
    fi

    # ---> Run code
    echo "Running GeN-Foam on $caseName"
    GeN-Foam -case $caseName 2>&1 | tee "$caseName/log.GeN-Foam"

    # ---> Kill gnuplot if it was started
    pkill -x gnuplot &> /dev/null &
done

#==============================================================================*
