#!/bin/sh
#----------------------------------------------------------------------------#
#       ______          _   __           ______                              #
#      / ____/  ___    / | / /          / ____/  ____   ____ _   ____ ___    #
#     / / __   / _ \  /  |/ /  ______  / /_     / __ \ / __ `/  / __ `__ \   #
#    / /_/ /  /  __/ / /|  /  /_____/ / __/    / /_/ // /_/ /  / / / / / /   #
#    \____/   \___/ /_/ |_/          /_/       \____/ \__,_/  /_/ /_/ /_/    #
#    Copyright (C) 2015 - 2022 EPFL                                          #
#----------------------------------------------------------------------------#

# Author: Thomas Guilbaud, 08/10/2022

# Run from this directory
cd ${0%/*} || exit 1

#==============================================================================*

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#==============================================================================*

createMesh() {
    # Recover variables
    case=$1
    region=$2
    unvMeshName=$3

    # Convert UNV mesh to OpenFOAM mesh
    ideasUnvToFoam $case/mesh/$unvMeshName -case $case

    # Remove existing polyMesh in the region
    rm -rf $case/constant/${region}/polyMesh
    mv $case/constant/polyMesh $case/constant/$region

    # createPatch -overwrite -case $case -region $region

    # Rescale the mesh
    transformPoints -scale 1e-2 -case $case -region $region

    # Check mesh quality
    checkMesh -case $case -region $region
}

# Create meshes for the regions
createMesh rootCase neutroRegion fuelAssemblyBafflePlenum_trianglesNeutro.unv
createMesh rootCase fluidRegion  fuelAssemblyBafflePlenum_triangles.unv

# Create baffles
createBaffles -case rootCase/ -region fluidRegion -overwrite

#==============================================================================*
