#!/bin/sh
#----------------------------------------------------------------------------#
#       ______          _   __           ______                              #
#      / ____/  ___    / | / /          / ____/  ____   ____ _   ____ ___    #
#     / / __   / _ \  /  |/ /  ______  / /_     / __ \ / __ `/  / __ `__ \   #
#    / /_/ /  /  __/ / /|  /  /_____/ / __/    / /_/ // /_/ /  / / / / / /   #
#    \____/   \___/ /_/ |_/          /_/       \____/ \__,_/  /_/ /_/ /_/    #
#    Copyright (C) 2015 - 2022 EPFL                                          #
#----------------------------------------------------------------------------#

cd ${0%/*} || exit 1    # Run from this directory

#==============================================================================*

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

endTimeSSN=1
endTimeSSTH=20


#==============================================================================*
# Neutronics steady-state
#==============================================================================*

cp -r rootCase steadyStateN

decomposePar -case steadyStateN -allRegions

# Set simulation variables
foamDictionary steadyStateN/system/controlDict -entry endTime -set $endTimeSSN
foamDictionary steadyStateN/system/controlDict -entry deltaT -set 1e-6
#foamDictionary steadyStateN/system/controlDict -entry solveFluidMechanics -set false
#foamDictionary steadyStateN/system/controlDict -entry solveEnergy -set false
foamDictionary steadyStateN/system/controlDict -entry regionSolvers/fluidRegion -remove
cp steadyStateN/constant/multiRegionCouplingDict_neutronSA steadyStateN/constant/multiRegionCouplingDict
#GeN-Foam -initializeMappedFields -case steadyStateN

# Run neutronics steady-state
mpirun -np 2 GeN-Foam -case steadyStateN -parallel |
    tee "steadyStateN/log.GeN-Foam" |
    grep --color=auto -e "Time = \|deltaT ="

reconstructPar -case steadyStateN -allRegions -latestTime
cp -r steadyStateN/0/fluidRegion steadyStateN/$endTimeSSN


#==============================================================================*
# Thermal-hydraulics steady-state
#==============================================================================*

cp -r steadyStateN steadyState

# Set simulation variables
decomposePar -case steadyState -region fluidRegion -time 1
foamDictionary steadyState/system/controlDict -entry endTime -set $endTimeSSTH
foamDictionary steadyState/system/controlDict -entry deltaT -set 2e-5 # 1e-5
foamDictionary steadyState/system/controlDict -entry adjustTimeStep -set true # false
foamDictionary steadyState/system/controlDict -entry regionSolvers/fluidRegion -set onePhase
cp steadyState/constant/multiRegionCouplingDict_coupled steadyState/constant/multiRegionCouplingDict
GeN-Foam -initializeMappedFields -case steadyState

# Run thermal-hydraulics steady-state
mpirun -np 2 GeN-Foam -case steadyState -parallel |
    tee "steadyState/log.GeN-Foam" |
    grep --color=auto -e "Time = \|deltaT ="

#==============================================================================*
