#!/bin/sh
# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh
runApplication -o changeDictionary
runApplication -o offbeat
#
runApplication -o postProcess -func sampleDict

stressSimulationIPyC=$(cat postProcessing/probes/0/sigma |tail -n 1| cut -d"(" -f2 | cut -d")" -f1 | cut -d" " -f6)
stressSimulationSiC=$(cat postProcessing/probes/0/sigma |tail -n 1| cut -d"(" -f3 | cut -d")" -f1 | cut -d" " -f6)

#
stressExptectedIPyC=-25e6
stressExptectedSiC=139.34e6
#
echo "Tangential stress at inner surface of IPyC: $stressSimulationIPyC" >> results
echo "Expected value: $stressExptectedIPyC" >> results
echo "Tangential stress at inner surface of SiC: $stressSimulationSiC" >> results
echo "Expected value: $stressExptectedSiC" >> results
#
relErrorIPyC=$(awk -v var1="$stressSimulationIPyC" \
                -v var2="$stressExptectedIPyC" \
                'BEGIN {print (100*(var1-var2)/var2)}')
relErrorSiC=$(awk -v var1="$stressSimulationSiC" \
                -v var2="$stressExptectedSiC" \
                'BEGIN {print (100*(var1-var2)/var2)}')

echo "Relative error for IPyC: $relErrorIPyC%" >> results
echo "Relative error for SiC: $relErrorSiC%" >> results
