#!/bin/sh
# Tutorial prepared based on the PhD work of Peter German (Texas A&M, peter.german@tamu.edu)

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


cases="steadyState transient transientEnd transient_substepping transientEnd_substepping"

runCloneCase()
{
    printf "Cloning $2 to case $1..."
    cp -r $2 $1
    printf "$2 cloned!\n"
}

setSteadyState()
{
    caseName=$1
    runCloneCase $caseName $2
    printf "Setting steady state case...\n"
    foamDictionary $caseName/system/controlDict -entry startFrom -set startTime
    foamDictionary $caseName/system/controlDict -entry startTime -set 0
    foamDictionary $caseName/system/controlDict -entry endTime -set 100
    foamDictionary $caseName/system/controlDict -entry adjustTimeStep -set true
    foamDictionary $caseName/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $caseName/system/controlDict -entry writeInterval -set 100
    cp dictionaries/steadyState/regionsDict $caseName/system/regionsDict
    GeN-Foam -initializeMappedFields -case $caseName
    printf "Case set!\n\n"
}


setTransient()
{
    caseName=$1
    runCloneCase $caseName $2
    cp -r $caseName/0/neutroRegion $caseName/100/
    cp -r $caseName/0/uniform $caseName/100/
    printf "Setting $caseName case...\n"
    foamDictionary $caseName/system/controlDict -entry startFrom -set startTime
    foamDictionary $caseName/system/controlDict -entry startTime -set 100
    foamDictionary $caseName/system/controlDict -entry endTime -set 400
    foamDictionary $caseName/system/controlDict -entry adjustTimeStep -set true
    foamDictionary $caseName/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $caseName/system/controlDict -entry writeInterval -set 10
    foamDictionary $caseName/system/controlDict -entry removeBaffles/neutroRegion -set false
    cp dictionaries/transient/regionsDict  $caseName/system/regionsDict
    GeN-Foam -initializeMappedFields -case $caseName
    printf "Case set!\n\n"
}

setTransientEnd()
{
    caseName=$1
    runCloneCase $1 $2
    printf "Setting $caseName case...\n"
    foamDictionary $caseName/system/controlDict -entry startFrom -set startTime
    foamDictionary $caseName/system/controlDict -entry startTime -set 400
    foamDictionary $caseName/system/controlDict -entry endTime -set 401
    foamDictionary $caseName/system/controlDict -entry adjustTimeStep -set true
    foamDictionary $caseName/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $caseName/system/controlDict -entry writeInterval -set 1
    GeN-Foam -initializeMappedFields -case $caseName
}

setTransient_substepping()
{
    caseName=$1
    runCloneCase $caseName $2
    cp -r $caseName/0/neutroRegion $caseName/100/
    cp -r $caseName/0/uniform $caseName/100/
    printf "Setting $caseName case...\n"
    foamDictionary $caseName/system/controlDict -entry startFrom -set startTime
    foamDictionary $caseName/system/controlDict -entry startTime -set 100
    foamDictionary $caseName/system/controlDict -entry endTime -set 400
    foamDictionary $caseName/system/controlDict -entry adjustTimeStep -set true
    foamDictionary $caseName/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $caseName/system/controlDict -entry writeInterval -set 10
    foamDictionary $caseName/system/controlDict -entry removeBaffles/neutroRegion -set false
    cp dictionaries/transient/regionsDict  $caseName/system/regionsDict
    printf '\nfuelZones\n(\n    core\n);\n\npseudoTimeSteps 100;\npseudoTimeStepSize 10.0;\npseudoTimeRelaxation 1.0;\n' >> $caseName/constant/neutroRegion/nuclearData
    GeN-Foam -initializeMappedFields -case $caseName
    printf "Case set!\n\n"
}

setTransientEnd_substepping()
{
    caseName=$1
    runCloneCase $1 $2
    printf "Setting $caseName case...\n"
    foamDictionary $caseName/system/controlDict -entry startFrom -set startTime
    foamDictionary $caseName/system/controlDict -entry startTime -set 400
    foamDictionary $caseName/system/controlDict -entry endTime -set 401
    foamDictionary $caseName/system/controlDict -entry adjustTimeStep -set true
    foamDictionary $caseName/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $caseName/system/controlDict -entry writeInterval -set 1
    foamDictionary $caseName/constant/neutroRegion/nuclearData -entry initPrecursorsLiquidFuel -set false
    GeN-Foam -initializeMappedFields -case $caseName
}

for caseName in $cases
do
    printf "Preparing to run case $caseName...\n"

    case "$caseName" in
        "steadyState")
            setSteadyState $caseName rootCase
            printf "Steady state th case is prepared!\n"
            ;;
        "transient")
            printf "Transient case entered...\n"
            setTransient $caseName steadyState
            ;;
        "transientEnd")
            printf "Transient case entered...\n"
            setTransientEnd $caseName transient
            ;;
        "transient_substepping")
            printf "Transient substepping case entered...\n"
            setTransient_substepping $caseName steadyState
            ;;
        "transientEnd_substepping")
            printf "Transient end substepping case entered...\n"
            setTransientEnd_substepping $caseName transient_substepping
            ;;
    esac

    # Start gnuplot if it exist
    if command -v gnuplot &> /dev/null
    then
        gnuplot -e "log='$caseName/log.GeN-Foam'" residuals - &> /dev/null &
    else
        echo "gnuplot could not be found"
    fi

    #( cd $caseName && runApplication `getApplication` )
    printf "Running GeN-Foam on $caseName\n"
    GeN-Foam -case $caseName 2>&1 | tee "$caseName/log.GeN-Foam"

    # Kill gnuplot if it was started
    pkill -x gnuplot &> /dev/null

done

#------------------------------------------------------------------------------
