#!/bin/sh
#----------------------------------------------------------------------------#
#       ______          _   __           ______                              #
#      / ____/  ___    / | / /          / ____/  ____   ____ _   ____ ___    #
#     / / __   / _ \  /  |/ /  ______  / /_     / __ \ / __ `/  / __ `__ \   #
#    / /_/ /  /  __/ / /|  /  /_____/ / __/    / /_/ // /_/ /  / / / / / /   #
#    \____/   \___/ /_/ |_/          /_/       \____/ \__,_/  /_/ /_/ /_/    #
#    Copyright (C) 2015 - 2022 EPFL                                          #
#----------------------------------------------------------------------------#

cd ${0%/*} || exit 1    # Run from this directory

#==============================================================================*

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#==============================================================================*

exe="GeN-Foam"

cases="steadyStateNSSP  steadyStateLPS "

runCloneCase()
{
    printf "Cloning $2 to case $1..."
    cp -r $2 $1
    printf "$2 cloned!\n"
}

setSteadyStateNSSP ()
{
    runCloneCase $1 $2
    printf "Setting steady state case using nuclearSteadyStatePebble...\n"
    cp dictionaries/NSSP/phaseProperties steadyStateNSSP/constant/fluidRegion/phaseProperties
    GeN-Foam -initializeMappedFields -case steadyStateNSSP
    printf "Case set!\n\n"
}


setSteadyStateLPS()
{
    runCloneCase $1 $2
    printf "Setting steady state case using lumpedParameterStructure...\n"
    cp dictionaries/LPS/phaseProperties steadyStateLPS/constant/fluidRegion/phaseProperties
    printf "Case set!\n\n"
}

for caseName in $cases
do
    printf "Preparing to run case $caseName...\n"

    case "$caseName" in
        "steadyStateNSSP")
            setSteadyStateNSSP $caseName rootCase
            printf "Steady state th case is prepared!\n"
            ;;
        "steadyStateLPS")
            printf "Transient case entered...\n"
            setSteadyStateLPS $caseName rootCase
            ;;
    esac

    # Start gnuplot if it exist
    if command -v gnuplot &> /dev/null
    then
        gnuplot -e "log='$caseName/log.$exe'" residuals - &> /dev/null &
    else
        echo "gnuplot could not be found"
    fi

    #( cd $caseName && runApplication `getApplication` )
    printf "Running $exe on $caseName\n"
    $exe -case $caseName 2>&1 | tee "$caseName/log.$exe"

    # Kill gnuplot if it was started
    pkill -x gnuplot &> /dev/null

done

#==============================================================================*
