import os
import pprint
import shutil
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

from foamForNuclear.boundaryConditions.slip import Slip
from foamForNuclear.checkvalue import check_type, check_value
from foamForNuclear.common import *
from foamForNuclear.createBafflesDict import BaffleDict
from foamForNuclear.topoSetDict import TopoSetAction
from .mesh import _LATTICE_TYPES, Mesh


class PolyMesh(Mesh):
    """
    Class object to handle and create polyMesh folder.

    If `srcpath` is provided: Copy a `polyMesh` folder in the current case.
    Else: Create a polyMesh using a Voronoi graph

    Parameters
    ----------
    region : str
        Name of the region
    srcpath : str
        Path of the `polyMesh` folder (default `None`).
    isOverwrite : bool
        If a `polyMesh` is already present in the case, can delete it and replace
        it by the `srcpath` (default `False`).
    """
    def __init__(
            self,
            region: str="",
            srcpath: str=None,#"./polyMesh",
            isOverwrite: bool=False
        ):
        super().__init__(region=region)

        self.srcpath = srcpath
        self.isOverwrite = isOverwrite

        self.pointsList = List([])
        self.faceList = List([])
        self.ownerList = List([])
        self.neighbourList = List([])
        self.boundaryList = List([])
        self.cellZonesList = List([])
        self.faceZonesList = List([])

        self.voronoiPoints = []
        self.uniqueCellZones = {}

        # Generated via pyvoro
        self.voronoiGraph = None


    @property
    def srcpath(self):
        return self._srcpath

    @srcpath.setter
    def srcpath(self, srcpath):
        check_type("srcpath", srcpath, str, none_ok=True)
        self._srcpath = srcpath

    @property
    def isOverwrite(self):
        return self._isOverwrite

    @isOverwrite.setter
    def isOverwrite(self, isOverwrite):
        check_type("isOverwrite", isOverwrite, bool)
        self._isOverwrite = isOverwrite


    @property
    def cellZones(self) -> list[str]:
        """
        Return the list of cellZone names.
        """
        if (self.srcpath is not None):
            filename = f"{self.srcpath}/cellZones"
            with open(filename, 'r') as f:
                for line in f:
                    if ("names" in line):
                        return(line.split()[3:-1])

        elif (not self.cellZonesList.is_empty):
            return([cellZone.name for cellZone in self.cellZonesList])

        return([])


    def add_voronoi_points_from_coordinates(
            self,
            coords: list[tuple] | list[list] | str,
            zLevel: float=None
        ):
        """
        Add cells using Honeycomb coordinates.
        Use the "Coordinates" function of https://foam-for-nuclear.gitlab.io/honeycomb/

        Parameters
        ----------
        coords : list[tuple] | list[list] | str
            If `coords` is a text, cell center coordinates in the following
            format `x;y;cellName`.
        zLevel : float
            Z-level in meter (default `None`) if coords is a string from
            Honeycomb.
        """
        check_type("zLevel", zLevel, (float, int), none_ok=True)

        if (isinstance(coords, str)):
            coords = [
                line.strip().split(';') for line in coords.split('\n')
                if line.strip() != "" and "#" not in line
            ]

        # Extract from coordinates
        # cellIdx = 0 if len(self.uniqueCellZones.keys()) == 0 else max([max(l) for l in self.uniqueCellZones.values()])
        cellIdx = len(self.voronoiPoints)
        for coord in coords:
            # Extract coordinates
            x, y = float(coord[0]), float(coord[1])
            if (zLevel is None):
                z = float(coord[2])
            else:
                z = zLevel

            self.voronoiPoints.append([x, y, z])

            # Extract unique zones in dict
            if (isinstance(coord[-1], str)):
                cellZoneName = coord[-1]
                if (cellZoneName not in self.uniqueCellZones):
                    self.uniqueCellZones[cellZoneName] = List([cellIdx])
                else:
                    self.uniqueCellZones[cellZoneName].append(cellIdx)

            cellIdx += 1


    def add_voronoi_points_from_lattice(
            self,
            lattice: str,
            nx: int,
            ny: int,
            pitch: float,
            latticeType: str,
            flatToFlatDirection: str='y',
            x: float=0,
            y: float=0,
            z: float=0,
            elementsToPlace: list[str] | str=None
        ):
        """
        Place the elementary submesh generated by funcElementGenerator using a
        lattice map.

        The lattice map can be a regular MCNP/Serpent format.
        Recommended use the Honeycomb tool
        https://foam-for-nuclear.gitlab.io/honeycomb/ to translate from OpenMC
        or CASMO.

        Usage ::

            # Define the lattice
            lattice = "
            0 0 W F W
             0 F F F F
              W F F F W
               F F F F 0
                W F W 0 0"

            mesh = ffn.PolyMesh()

            mesh.add_voronoi_points_from_lattice(
                lattice=lattice,
                latticeType="hexagon",
                nx=5, ny=5, pitch=latticePitch,
                elementsToPlace=["F", "W"]
            )

        Parameters
        ----------
        lattice : str
            Lattice map in text format, see Usage
        nx : int
            Number of rows in the lattice
        ny : int
            Number of columns in the lattice
        pitch : float
            Pitch of the lattice
        latticeType : str {"hexagon" or "square"}
            Lattice type.
        flatToFlatDirection : str {"x", "y"}
            Flat to flat alignment direction, (default `'y'`).
        x : float
            Offset in the X-direction (default `0`).
        y : float
            Offset in the Y-direction (default `0`).
        z : float
            Offset in the Z-direction (default `0`).
        elementsToPlace : list[str] | str | None
            Elements present in the lattice to be placed. If None (default) is
            found, place all the non-0 elements in the lattice.
        """

        latticeElements = self.getLatticeAsList(
            lattice=lattice,
            nx=nx, ny=ny,
            pitch=pitch,
            latticeType=latticeType,
            flatToFlatDirection=flatToFlatDirection,
            x=x, y=y,
            elementsToPlace=elementsToPlace
        )

        coords = [
            [coord0, coord1, z, elementName]
            for elementName, coord0, coord1 in latticeElements
        ]

        self.add_voronoi_points_from_coordinates(coords=coords)


    def generate_mesh_from_voronoi_points(
            self,
            boundaryBox: list[list[float]]=None,
            cylinderRadius: float=None,
            cylinderZmin: float=None,
            cylinderZmax: float=None,
            cellZonesToStrip: list[str]=[],
            isAddInletOuletBC: bool=False,
            isAddBaffles: bool=False
        ):
        """
        Generate the PolyMesh objects. Don't dump the `polyMesh` folder.
        If `cylinderRadius` is not `None`, truncate the boundary mesh into a
        cylinder.

        Notes:

        - Using the `isAddBaffles` to `True` may cause the creation of a \
            `polyMesh/sets/nonManifoldPoints` file that is the result of a \
            non-coplanar faceZone. To-do test not affecting the results.
        - To be replaced by scipy.spatial.Voronoi?: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Voronoi.html#scipy.spatial.Voronoi

        Parameters
        ----------
        boundaryBox : list[list[float]]
            X, Y and Z bounds of the bounding box (i.e
            `[[-1, 1], [-1, 1], [-1, 1]]`)
        cylinderRadius : float
            Replace the bounding box into a cylinder of radius `cylinderRadius`
            (default `None`).
        cylinderZmin : float
            Replace the bounding box into a cylinder of min Z `cylinderZmin`
            (default `None`).
        cylinderZmax : float
            Replace the bounding box into a cylinder of max Z `cylinderZmax`
            (default `None`).
        cellZonesToStrip : list[str]
            List of cellZone names to be removed from the mesh. Can be used to
            have a perfect lattice without the boundary box (default `[]`).
        isAddInletOuletBC : bool
            If True, add the `inlet` and `outlet` boundary conditions assuming
            that the `inlet` is the lowest face along the Z-direction and
            `outlet` is the highest face along the Z-direction (default `False`).
        isAddBaffles : bool
            If true, create baffles along the Z-direction assuming that all the
            non-baffle faces are normal to the Z-direction (default `False`).
        """
        try:
            import pyvoro
        except ModuleNotFoundError:
            msg = "No module pyvoro installed"
            raise ModuleNotFoundError(msg)

        limits = boundaryBox

        if (boundaryBox is None):
            # Use cylindrical bounding box
            if (cylinderRadius is None or cylinderZmin is None or cylinderZmax is None):
                msg = "Provide either 'boundaryBox' or ('cylinderRadius' and 'cylinderZmin' and 'cylinderZmax')"
                raise ValueError(msg)

            limits = [
                [-cylinderRadius, cylinderRadius],
                [-cylinderRadius, cylinderRadius],
                [cylinderZmin, cylinderZmax]
            ]

        # Reset lists
        self.faceZonesList = List([])
        self.cellZonesList = List([])
        self.faceList = List([])
        self.ownerList = List([])
        self.neighbourList = List([])
        self.pointsList = List([])

        # Use pyvoro to compute the Voronoi tessellation
        # the second argument gives the the axis limits in x,y and z direction
        # the third argument gives "dispersion = max distance between two points
        # that might be adjacent" (not sure how exactly this works)
        self.voronoiGraph = pyvoro.compute_voronoi(
            self.voronoiPoints,
            limits=limits,
            dispersion=1,
        )


        # Strip specific cells
        cellsToStrip = []
        for cellZoneName, cellIndices in self.uniqueCellZones.items():
            if (cellZoneName in cellZonesToStrip):
                cellsToStrip += cellIndices

        for i, celli in enumerate(self.voronoiGraph):
            for j, facej in enumerate(celli['faces']):
                if (facej['adjacent_cell'] in cellsToStrip):
                    if (facej['adjacent_cell'] > 0):
                        self.voronoiGraph[i]['faces'][j]['adjacent_cell'] = -facej['adjacent_cell']
                    else:
                        self.voronoiGraph[i]['faces'][j]['adjacent_cell'] = -len(self.voronoiGraph)-1


        # Fill face, owner and neighbour lists
        pointIdx, cellIdxI = 0, 0
        allVertices, adjacentCells = [], []
        newCellIndices = {}
        for celli, vnoicell in enumerate(self.voronoiGraph):
            if (celli in cellsToStrip):
                continue

            # If cellZonesToStrip is empty, cellIdxI MUST be equal to celli
            newCellIndices[celli] = cellIdxI

            # The vertices are the corner points of the Voronoi cell
            voronoiVertices = vnoicell['vertices']

            for vertex in voronoiVertices:
                xVertex, yVertex, zVertex = vertex[0], vertex[1], vertex[2]

                # If points outside the cylinder bounding box, rescale based on
                # radial distance
                if (cylinderRadius is not None):
                    ri = np.sqrt(xVertex**2 + yVertex**2)
                    if (ri > cylinderRadius):
                        xVertex *= cylinderRadius / ri
                        yVertex *= cylinderRadius / ri

                allVertices.append(Vector(xVertex, yVertex, zVertex))


            # Cycle through all faces of the polygon
            for facei in vnoicell['faces']:
                # Reverse vertice loop to be OpenFOAM compliant, the face needs
                # to point outward from the cell
                loopVertices = [idx + pointIdx for idx in facei['vertices']][::-1]

                # If negative -> boundary face
                if (facei['adjacent_cell'] < 0):
                    self.ownerList.append(cellIdxI)
                    self.faceList.append(List(loopVertices))

                # Internal face part of the owner -> avoid double counting
                elif (facei['adjacent_cell'] >= 0):
                    cellIdxJ = -1
                    for cellj, vnoicellj in enumerate(self.voronoiGraph):
                        if (cellj in cellsToStrip):
                            continue
                        cellIdxJ += 1

                        # Continue if adjacent cell already encounter
                        if ((celli, cellj) in adjacentCells or (cellj, celli) in adjacentCells):
                            continue

                        isBreak = False
                        for facej in vnoicellj['faces']:
                            if (cellj == facei['adjacent_cell'] and celli == facej['adjacent_cell']):
                                self.ownerList.insert(len(self.neighbourList), cellIdxI)
                                self.faceList.insert(len(self.neighbourList), List(loopVertices))
                                self.neighbourList.append(cellIdxJ)

                                adjacentCells.append((celli, cellj))

                                isBreak = True
                                break

                        if (isBreak):
                            break

            pointIdx += len(voronoiVertices)
            cellIdxI += 1


        # Check coincident points
        newPointsIdx = {}
        for i, pointI in enumerate(allVertices):
            isDuplicatePoint = False
            for j, pointJ in enumerate(self.pointsList):
                # Same point coord -> remove the point I
                if (pointI == pointJ):
                    isDuplicatePoint = True
                    newPointsIdx[i] = j
                    break

            if (not isDuplicatePoint):
                newPointsIdx[i] = len(self.pointsList)
                self.pointsList.append(pointI)


        # Renumber vertex indices in the face list
        for faceIdx, face in enumerate(self.faceList):
            for vertexIdx, vertexI in enumerate(face):
                self.faceList[faceIdx][vertexIdx] = newPointsIdx[vertexI]


        # Create cellZones
        for cellZoneName, cellIndices in self.uniqueCellZones.items():
            if (cellZoneName in cellZonesToStrip):
                continue

            cellIndices = List([newCellIndices[celli] for celli in cellIndices])

            self.cellZonesList.append(OpenFOAMDict(
                items={
                    'type': 'cellZone',
                    'cellLabels      List<label>': cellIndices.__repr__(isAddLength=True)
                },
                name=cellZoneName
            ))


        # Create baffle faces
        if (isAddBaffles):
            baffleFaceSet = List([])
            # Compute face direction, assumes baffles faces are not along the
            # Z-direction AND are not part of the boundary faces
            for faceIdx, face in enumerate(self.faceList):
                vertexZ = [self.pointsList[vertexI].z for vertexI in face]
                if (
                    not all([abs((z-vertexZ[0])/vertexZ[0]) < 1e-6 for z in vertexZ])
                    and faceIdx < len(self.neighbourList)
                ):
                    baffleFaceSet.append(faceIdx)

            self.faceZonesList.append(OpenFOAMDict(
                items={
                    'type': 'faceZone',
                    'faceLabels      List<label>': baffleFaceSet.__repr__(isAddLength=True),
                    'flipMap': f'List<bool> {len(baffleFaceSet)} {"{1}"}'
                },
                name="baffleZone"
            ))
            # self.createBafflesDict.add_baffle_mapped_wall(
            #     name="baffleZone",
            #     zoneName="baffleZone"
            # )
            baffleDict = BaffleDict(
                name="baffleZone",
                faceType="faceZone",
                zoneName="baffleZone",
                masterType="mappedWall",
                slaveType="mappedWall",
                sampleMode="nearestPatchFace",
                sampleRegion=self.region,
                offsetMode="uniform",
                transform="coincidentFullMatch",
                offset=Vector(0, 0, 0)
            )
            baffleDict.add_field_boundary_condition('U', Slip())
            self.createBafflesDict.append(baffleDict)


        # Create a global boundary condition
        self.boundaryList.append(OpenFOAMDict(
            items={
                'type': 'patch',
                'nFaces': len(self.faceList)-len(self.neighbourList),
                'startFace': len(self.neighbourList)
            },
            name="defaultFaces"
        ))

        if (isAddInletOuletBC):
            minZ = min([p.z for p in self.pointsList])
            maxZ = max([p.z for p in self.pointsList])

            self.topoSetDict.append(
                TopoSetAction(
                    name='inlet_pointSet',
                    setType='pointSet',
                    actionType='new',
                    sourceType='clipPlaneToPoint',
                    extraParameters={
                        'point': Vector(0, 0, minZ + 1e-8),
                        'normal': Vector(0, 0, -1)
                    }
                )
            )
            self.topoSetDict.append(
                TopoSetAction(
                    name='inlet_faceSet',
                    setType='faceSet',
                    actionType='new',
                    sourceType='pointToFace',
                    extraParameters={
                        'set': 'inlet_pointSet',
                        'option': 'all'
                    }
                )
            )
            self.topoSetDict.append(
                TopoSetAction(
                    name='outlet_pointSet',
                    setType='pointSet',
                    actionType='new',
                    sourceType='clipPlaneToPoint',
                    extraParameters={
                        'point': Vector(0, 0, maxZ - 1e-8),
                        'normal': Vector(0, 0, 1)
                    }
                )
            )
            self.topoSetDict.append(
                TopoSetAction(
                    name='outlet_faceSet',
                    setType='faceSet',
                    actionType='new',
                    sourceType='pointToFace',
                    extraParameters={
                        'set': 'outlet_pointSet',
                        'option': 'all'
                    }
                )
            )

            self.createPatchDict.add_patch(
                name="inlet",
                regex="inlet_faceSet",
                patchType='patch',
                constructFrom="set"
            )
            self.createPatchDict.add_patch(
                name="outlet",
                regex="outlet_faceSet",
                patchType='patch',
                constructFrom="set"
            )


    def createPointsFile(self, pointsList: List) -> None:
        with open(f"constant/{self.region}/polyMesh/points", "w") as f:
            text = ""
            text += openfoamHeader

            text += openfoamFileHeader("points", className="vectorField")

            text += pointsList.__repr__(isAddLength=True)

            text += openfoamFooterLine

            f.write(text)


    def createFacesFile(self, faceList: List):
        with open(f"constant/{self.region}/polyMesh/faces", "w") as f:
            text = ""
            text += openfoamHeader

            text += openfoamFileHeader("faces", className="faceList")

            text += f"{len(faceList)}\n(\n"
            for face in faceList:
                text += face.__repr__(noBreak=True, isAddLength=True) + "\n"
            text += ")\n"

            text += openfoamFooterLine

            f.write(text)


    def createOwnerFile(self, ownerList: List):
        with open(f"constant/{self.region}/polyMesh/owner", "w") as f:
            text = ""
            text += openfoamHeader

            text += openfoamFileHeader("owner", className="labelList")

            text += ownerList.__repr__(isAddLength=True)

            text += openfoamFooterLine

            f.write(text)


    def createNeighbourFile(self, neighbourList: List):
        with open(f"constant/{self.region}/polyMesh/neighbour", "w") as f:
            text = ""
            text += openfoamHeader

            text += openfoamFileHeader("neighbour", className="labelList")

            text += neighbourList.__repr__(isAddLength=True)

            text += openfoamFooterLine

            f.write(text)


    def createBoundaryFile(self, boundaryList: List):
        with open(f"constant/{self.region}/polyMesh/boundary", "w") as f:
            text = ""
            text += openfoamHeader

            text += openfoamFileHeader("boundary", className="polyBoundaryMesh")

            text += boundaryList.__repr__(isAddLength=True)

            text += openfoamFooterLine

            f.write(text)


    def createCellZonesFile(self, cellZonesList: List):
        with open(f"constant/{self.region}/polyMesh/cellZones", "w") as f:
            text = ""
            text += openfoamHeader

            text += openfoamFileHeader("cellZones", className="regIOobject")

            text += cellZonesList.__repr__(isAddLength=True)

            text += openfoamFooterLine

            f.write(text)


    def createFaceZonesFile(self, faceZonesList: List):
        with open(f"constant/{self.region}/polyMesh/faceZones", "w") as f:
            text = ""
            text += openfoamHeader

            text += openfoamFileHeader("faceZones", className="regIOobject")

            text += faceZonesList.__repr__(isAddLength=True)

            text += openfoamFooterLine

            f.write(text)


    def createFaceSet(self, faceSetName: str, faceSet: List):
        setsPath = f"constant/{self.region}/polyMesh/sets"
        if (not os.path.isdir(setsPath)):
            os.mkdir(setsPath)

        with open(f"{setsPath}/{faceSetName}", "w") as f:
            text = ""
            text += openfoamHeader

            text += openfoamFileHeader(faceSetName, className="faceSet")

            text += faceSet.__repr__(isAddLength=True)

            text += openfoamFooterLine

            f.write(text)


    def export_to_openfoam(self):
        Mesh.export_to_openfoam(self)

        path = f"constant/{self.region}/polyMesh"

        # If overwrite is true, remove the current polyMesh
        if (self.isOverwrite):
            try:
                shutil.rmtree(path)
            except:
                pass

        # Duplicate a mesh from elsewhere if the path doesn't exist
        if (not os.path.isdir(path) and self.srcpath is not None):
            copyFolder(self.srcpath, path)

        # Create the mesh
        else:
            os.mkdir(path)

            self.createPointsFile(pointsList=self.pointsList)
            self.createFacesFile(faceList=self.faceList)
            self.createOwnerFile(ownerList=self.ownerList)
            self.createNeighbourFile(neighbourList=self.neighbourList)
            self.createBoundaryFile(boundaryList=self.boundaryList)
            self.createCellZonesFile(cellZonesList=self.cellZonesList)
            self.createFaceZonesFile(faceZonesList=self.faceZonesList)
            # if (not self.baffleSet.is_empty):
            #     self.createFaceSet(faceSetName="baffleSet", faceSet=self.baffleSet)


    def plot_voronoi_cells(self):
        rng = np.random.default_rng(11)

        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')

        # for each Voronoi cell, plot all the faces of the corresponding polygon
        for vnoicell in self.voronoiGraph:
            faces = []
            # the vertices are the corner points of the Voronoi cell
            vertices = np.array(vnoicell['vertices'])
            # cycle through all faces of the polygon
            for face in vnoicell['faces']:
                faces.append(vertices[np.array(face['vertices'])])

            # join the faces into a 3D polygon
            polygon = Poly3DCollection(
                faces,
                alpha=0.5,
                facecolors=rng.uniform(0,1,3),
                linewidths=0.5,
                edgecolors='black'
            )
            ax.add_collection3d(polygon)

        return(fig, ax)
