#!/bin/bash
#----------------------------------------------------------------------------#
#       ______          _   __           ______                              #
#      / ____/  ___    / | / /          / ____/  ____   ____ _   ____ ___    #
#     / / __   / _ \  /  |/ /  ______  / /_     / __ \ / __ `/  / __ `__ \   #
#    / /_/ /  /  __/ / /|  /  /_____/ / __/    / /_/ // /_/ /  / / / / / /   #
#    \____/   \___/ /_/ |_/          /_/       \____/ \__,_/  /_/ /_/ /_/    #
#    Copyright (C) 2015 - 2022 EPFL                                          #
#----------------------------------------------------------------------------#

cd ${0%/*} || exit 1    # Run from this directory

#==============================================================================*

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#==============================================================================*

exe="GeN-Foam"

endTimeSS=900
endTimeT=1200

cases="steadyState transient"

runCloneCase()
{
    printf "Cloning $2 to case $1\n"
    cp -r $2 $1
    printf "$2 cloned!\n"
}

setSteadyState()
{
    runCloneCase $1 $2

    printf "Setting steady state case\n"

    foamDictionary $1/system/controlDict -entry endTime -set $endTimeSS
    # foamDictionary $1/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $1/system/controlDict -entry writeInterval -set $endTimeSS
    foamDictionary $1/system/controlDict -entry maxCo -set 50.0
    foamDictionary $1/system/controlDict -entry maxDeltaT -set 2.0
    foamDictionary $1/system/controlDict -entry removeBaffles.fluidRegion -set true
    cp dictionaries/steadyState/regionsDict $1/system/regionsDict
    GeN-Foam -initializeMappedFields -case $1
    printf "Case set!\n\n"
}

setTransient()
{
    runCloneCase $1 $2

    printf "Setting transient case\n"

    for i in {0..4}
    do
        cp -r $1/processor$i/0/neutroRegion $1/processor$i/$endTimeSS/
        cp -r $1/processor$i/0/uniform/reactorState $1/processor$i/$endTimeSS/uniform
    done

    # Set the power density field for PK solver
    foamDictionary $1/system/controlDict -entry removeBaffles.neutroRegion -set false
    reconstructPar -allRegions -latestTime -case $1
    foamListTimes -rm -processor -case $1
    cp dictionaries/PKInitialization/regionsDict $1/system/regionsDict
    GeN-Foam -initializeMappedFields -case $1
    decomposePar -allRegions -latestTime -case $1 -copyUniform

    # Set transient case
    foamDictionary $1/system/controlDict -entry endTime -set $endTimeT
    foamDictionary $1/system/controlDict -entry writeControl -set timeStep
    foamDictionary $1/system/controlDict -entry writeInterval -set 50
    foamDictionary $1/system/controlDict -entry maxCo -set 1.0;
    foamDictionary $1/constant/neutroRegion/neutronicsProperties -entry eigenvalueNeutronics -set false
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.h -set 0.8
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.hFinal -set 1.0
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.U -set 0.8
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.UFinal -set 1.0
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.p_rgh -set 0.8
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.p_rghFinal -set 1.0
    foamDictionary $1/system/controlDict -entry maxDeltaT -set 1;
    cp dictionaries/transient/regionsDict $1/system/regionsDict
    GeN-Foam -initializeMappedFields -case $1
    printf "Case set!\n\n"
}

for caseName in $cases
do
    if [ ! -d $caseName ]
    then
        printf "Preparing to run case $caseName\n"

        case "$caseName" in
            "steadyState")
                setSteadyState $caseName rootCase
                decomposePar -case $caseName -allRegions -copyUniform
                ;;
            "transient")
                setTransient $caseName steadyState
                ;;
        esac

        # Start gnuplot if it exist
        if command -v gnuplot &> /dev/null
        then
            gnuplot -e "log='$caseName/log.$exe'" residuals - &> /dev/null &
        else
            echo "gnuplot could not be found"
        fi

        touch $caseName/foam.foam

        printf "Running $exe on $caseName\n"
        mpirun -np 5 $exe -parallel -case $caseName | tee "$caseName/log.$exe"

        # Kill gnuplot if it was started
        pkill -x gnuplot &> /dev/null

        # case "$caseName" in
        #     "transient")
        #     reconstructPar -case $caseName -allRegions
        #     ;;
        # esac
    else
        echo "$caseName case already exist"
    fi
done

#==============================================================================*
