#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Clean the case
foamListTimes -rm # Remove all time directories
rm -r postProcessing # Remove post-processing directories
rm log.* # Remove log files
rm temperaturePlot.png # Remove temperature plot image
