#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Clean the case
foamListTimes -rm # Remove all time directories
rm -rf postProcessing # Remove post-processing directories
rm -f log.* # Remove log files
rm -f temperaturePlot.png # Remove temperature plot image
