#!/bin/bash

# Source OpenFOAM run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# --- Run CHTLoop
echo "Running CHTLoop..."
GeN-Foam -case CHTLoop | tee CHTLoop/log.GeN-Foam

# --- Run boundaryCoupling
echo "Running boundaryCoupling..."
GeN-Foam -case boundaryCoupling | tee boundaryCoupling/log.GeN-Foam
