#!/bin/sh
# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh
runApplication -o changeDictionary
runApplication -o offbeat

initial=$(grep -i "Initial Cs amount" log.offbeat | tail -n 1| cut -d" " -f4)
Cs1=$(grep -i "Released Cs amount" log.offbeat | tail -n 1| cut -d" " -f4)

solverDict='./constant/solverDict'

runApplication -o foamDictionary $solverDict -entry materials/SiC/crackFpRelease -set true
#
runApplication -o offbeat

Cs2=$(grep -i "Released Cs amount" log.offbeat | tail -n 1| cut -d" " -f4)
#
totalCs=$(awk -v var1="$Cs1" \
                -v var2="$Cs2" \
                'BEGIN {print (var1+var2)}')

fractionRelease=$(awk -v var1="$totalCs" \
                -v var2="$initial" \
                'BEGIN {print (var1/var2)}')

CsExpected=0.999992
#
echo "Released Cs: $totalCs" >> results
echo "Released Cs fraction: $fractionRelease" >> results
echo "Codes range: [0.999, 1.000]" >> results
echo "Expected value: $CsExpected" >> results
#
relError=$(awk -v var1="$fractionRelease" \
                -v var2="$CsExpected" \
                'BEGIN {print (100*(var1-var2)/var2)}')

echo "Relative change: $relError%" >> results

runApplication -o foamDictionary $solverDict -entry materials/SiC/crackFpRelease -set false
