#!/bin/bash

cases="fixedInnerHeatFlux
       fixedInterfaceTemperature"
    #    kineticsModels_highT_01
    #    kineticsModels_highT_02
    #    kineticsModels_lowT_01
    #    kineticsModels_lowT_02"

echo $cases
for case in $cases
do
    echo Cleaning $case
    cd $case
    ./Allclean
    cd ..
done

rm -f results
