[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "foamForNuclear"
authors = [
    {name = "The FoamForNuclear Development Team"},
]
description = "FoamForNuclear Python API"
requires-python = ">=3.10"
license = {file = "LICENSE"}
version = "2506"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU GPL v3",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "psutil",
    "numpy",
    "matplotlib",
    "uncertainties",
    "foamlib",
    "serpentTools",
    "pyvista",
    "python_mermaid",
    "fmpy",
    "omsimulator",
    "pandas",
    # "pyvoro",
    "tqdm",
    "requests",
]

[project.optional-dependencies]
openmc = ["openmc"]

[project.urls]
Homepage = "https://gitlab.com/foam-for-nuclear/foam-for-nuclear-repository"
Documentation = "https://foam-for-nuclear.gitlab.io/foam-for-nuclear-repository/"
Repository = "https://gitlab.com/foam-for-nuclear/foam-for-nuclear-repository"
Issues = "https://gitlab.com/foam-for-nuclear/foam-for-nuclear-repository/-/issues"

[tool.setuptools.packages.find]
include = ['foamForNuclear*']
exclude = ['tests*']

[tool.setuptools.package-data]
