#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh
runApplication -o changeDictionary
runApplication -o offbeat 
paraFoam -touch

fname="log.offbeat" 

pattern="Gap volume" 
if [ -f "$fname" ]
then
    result=$(grep -i "$pattern" "$fname")
    for word in $result; do
        gapVolume=$word
    done
fi

pattern="Top plenum volume" 
if [ -f "$fname" ]
then
    result=$(grep -i "$pattern" "$fname")
    for word in $result; do
        topVolume=$word
    done
fi

pattern="Bottom plenum volume" 
if [ -f "$fname" ]
then
    result=$(grep -i "$pattern" "$fname")
    for word in $result; do
        bottomVolume=$word
    done
fi

echo "Gap volume: $gapVolume" >> results
echo "Top plenum volume: $topVolume" >> results
echo "Bottom plenum volume: $bottomVolume" >> results

totVolume=$(awk -v var1="$gapVolume" \
                -v var2="$topVolume" \
                -v var3="$bottomVolume" \
                'BEGIN {print (var1+var2+var3)}')

echo "Total volume: $totVolume" >> results

expectedVolume=1.37734E-07
echo "Expected volume: $expectedVolume" >> results

relError=$(awk -v var1="$totVolume" \
               -v var2="$expectedVolume" \
               'BEGIN {print 100*(var1-var2)/var2}')


echo "Relative error: $relError%"  >> results

