#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory
set -o pipefail

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh

rm -f results
STATUS=0

runApplication -o foamDictionary constant/solverDict -entry mechanicsSolver -set $solver
runApplication -o foamListTimes -rm
rm -rf postProcessing

runApplication -o offbeat

if [[ $WM_PROJECT_VERSION == *v* ]]
then    
    runApplication -o postProcess -func xyGraph_ESI
    gnuplot plots.gnuplot > log.gnuplot 
    python3 test_ESI.py | tee -a results
else
    runApplication -o postProcess -func xyGraph 
    gnuplot plots.gnuplot > log.gnuplot 
    python3 test.py | tee -a results
fi

STATUS=$(expr $? "|" $STATUS)

echo "" | tee -a results

exit $STATUS

#------------------------------------------------------------------------------
