#!/bin/sh
#----------------------------------------------------------------------------#
#       ______          _   __           ______                              #
#      / ____/  ___    / | / /          / ____/  ____   ____ _   ____ ___    #
#     / / __   / _ \  /  |/ /  ______  / /_     / __ \ / __ `/  / __ `__ \   #
#    / /_/ /  /  __/ / /|  /  /_____/ / __/    / /_/ // /_/ /  / / / / / /   #
#    \____/   \___/ /_/ |_/          /_/       \____/ \__,_/  /_/ /_/ /_/    #
#    Copyright (C) 2015 - 2022 EPFL                                          #
#----------------------------------------------------------------------------#

cd ${0%/*} || exit 1    # Run from this directory

#------------------------------------------------------------------------------

tutorials="
    1D_boiling
    1D_CHF/imposedPower
    1D_CHF/imposedTemperature
    1D_HX/onePhase
    1D_HX/twoPhase
    1D_MSR_pointKinetics
    1D_PSBT_SC
    1D_thermalMSR_pointKinetics
    2D_cavityBoussinesq
    2D_externalSourceDiffusion
    2D_fullCoupling
    2D_FFTF
    2D_KNS37-L22
    2D_MSFR
    2D_onePhaseAndPointKineticsCoupling
    2D_onePhaseAndSubcriticalPointKineticsCoupling
    2D_voidMotionNoPhaseChange
    3D_gFHR
    3D_NTPfuelAssembly
    3D_SmallESFR
    Godiva_SN
    testing/2D_MSFR_ULOF_diffusion_and_pk
    testing/FMU/2D_onePhaseAndPointKineticsCouplingExternalReacivityFMI/comparisonFMU
    testing/FMU/2D_onePhaseAndPointKineticsCouplingExternalReacivityFMI/PIDcontrol
    testing/FMU/powerTemperatureMomentumControl
    toBeUpdated/2D_RegressionESFR
" 

# run all tutorials and check for clean finish 
for tutorialName in $tutorials
do

    case "$tutorialName" in
    "3D_SmallESFR")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "1D_boiling")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "1D_PSBT_SC")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "1D_MSR_pointKinetics")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "1D_thermalMSR_pointKinetics")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "1D_HX/onePhase")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ../..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "1D_HX/twoPhase")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ../..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "1D_CHF/imposedPower")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ../..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "1D_CHF/imposedTemperature")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ../..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "2D_MSFR")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "2D_FFTF")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;        
    "2D_cavityBoussinesq")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "2D_externalSourceDiffusion")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
     "2D_fullCoupling")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "2D_onePhaseAndPointKineticsCoupling")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "2D_onePhaseAndSubcriticalPointKineticsCoupling")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "2D_voidMotionNoPhaseChange")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;   
    "2D_KNS37-L22")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "Godiva_SN")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "3D_gFHR")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "3D_NTPfuelAssembly")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "testing/2D_MSFR_ULOF_diffusion_and_pk")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        ./Allclean
        cd ../..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "testing/FMU/2D_onePhaseAndPointKineticsCouplingExternalReacivityFMI/comparisonFMU")
        printf "Cleaning tutorial $tutorialName...\n"
        path=$(pwd)
        cd $tutorialName
        ./Allclean
        cd $path
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "testing/FMU/2D_onePhaseAndPointKineticsCouplingExternalReacivityFMI/PIDcontrol")
        printf "Cleaning tutorial $tutorialName...\n"
        path=$(pwd)
        cd $tutorialName
        ./Allclean
        cd $path
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "testing/FMU/powerTemperatureMomentumControl")
        printf "Cleaning tutorial $tutorialName...\n"
        path=$(pwd)
        cd $tutorialName
        ./Allclean
        cd $path
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;
    "toBeUpdated/2D_RegressionESFR")
        printf "Cleaning tutorial $tutorialName...\n"
        cd $tutorialName
        python3 Allclean.py
        cd ../..
        printf "Done cleaning tutorial $tutorialName...\n"
        ;;           
    esac

done


# clean all

#------------------------------------------------------------------------------
