#!/bin/sh
#----------------------------------------------------------------------------#
#       ______          _   __           ______                              #
#      / ____/  ___    / | / /          / ____/  ____   ____ _   ____ ___    #
#     / / __   / _ \  /  |/ /  ______  / /_     / __ \ / __ `/  / __ `__ \   #
#    / /_/ /  /  __/ / /|  /  /_____/ / __/    / /_/ // /_/ /  / / / / / /   #
#    \____/   \___/ /_/ |_/          /_/       \____/ \__,_/  /_/ /_/ /_/    #
#    Copyright (C) 2015 - 2022 EPFL                                          #
#----------------------------------------------------------------------------#

cd ${0%/*} || exit 1    # Run from this directory

#==============================================================================*

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cases="legacyThermoMechanics extendedThermoMechanics"

for caseName in $cases
do
    printf "Preparing to run case $caseName...\n"

    # Start gnuplot if it exist
    if command -v gnuplot &> /dev/null
    then
        gnuplot -e "log='$caseName/log.GeN-Foam'" residuals - &> /dev/null &
    else
        echo "gnuplot could not be found"
    fi

    printf "Running GeN-Foam on $caseName\n"
    decomposePar -case $caseName -allRegions -copyUniform
    mpirun -np 4 GeN-Foam -parallel -case $caseName | tee "$caseName/log.GeN-Foam"

    # Kill gnuplot if it was started
    pkill -x gnuplot &> /dev/null

done

#------------------------------------------------------------------------------
