#!/bin/sh
# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh
runApplication -o changeDictionary
runApplication -o offbeat
#
runApplication -o postProcess -func sampleDict

pressureSimulation=$(grep -i "Gas pressure" log.offbeat | tail -n 1| cut -d" " -f3)
stressSimulationSiC=$(cat postProcessing/probes/0/sigma |tail -n 1| cut -d"(" -f2 | cut -d")" -f1 | cut -d" " -f6)

fname="log.offbeat"

pattern="Gap volume"
if [ -f "$fname" ]
then
    result=$(grep -i "$pattern" "$fname")
    for word in $result; do
        gapVolume=$word
    done
fi
#
pressureExpected=1.43578e+07
stressExpectedSiC=-1.34632e+08
#
echo "Internal pressure: $pressureSimulation" >> results
echo "Previous value: $pressureExpected" >> results
echo "Range of other codes: [12e6, 84e6]" >> results
echo "Tangential stress at inner surface of SiC: $stressSimulationSiC" >> results
echo "Previous value: $stressExpectedSiC" >> results
echo "Range of other codes: [-127e6, 426e6]" >> results
#
relErrorIPyC=`echo - | awk '{print 100*(var1-var2)/var2}' \
var1="$pressureSimulation" var2="$pressureExpected"`
relErrorSiC=`echo - | awk '{print 100*(var1-var2)/var2}' \
var1="$stressSimulationSiC" var2="$stressExpectedSiC"`

echo "Relative change for gas pressure: $relErrorIPyC%" >> results
echo "Relative change for SiC: $relErrorSiC%" >> results
