#!/usr/bin/env python3
"""
AI-enhanced documentation generator for foamForNuclear.

Browses all yaml sidecar files and source code to:
  - Generate yaml files for undocumented classes
  - Check consistency of existing yaml files with source code
  - Add theory/formulation sections
  - Scan all repo files for inappropriate content

Run from the repository root:
  python3 tools/docAI/doc_ai.py --help

Requires:
  pip install openai pyyaml
  export OPENAI_API_KEY=sk-...
"""

import argparse
import difflib
import hashlib
import json
import os
import re
import sys
import time
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    print("Error: pyyaml not found. Install with: pip install pyyaml")
    sys.exit(1)

try:
    from openai import OpenAI
except ImportError:
    print("Error: openai package not found. Install with: pip install openai")
    sys.exit(1)


# =============================================================================
# Repository layout constants
# =============================================================================

# Locate repo root relative to this script: tools/docAI/doc_ai.py
_SCRIPT_DIR = Path(__file__).parent.resolve()
REPO_ROOT = _SCRIPT_DIR.parent.parent.resolve()

# Yaml files in these dirs will be skipped
EXCLUDE_YAML_PARTS = {"lnInclude", "Make", "thirdParty", "documentation", "tools"}

# Warning marker that means the yaml is auto-generated / incomplete
INCOMPLETE_MARKER = "Preliminary autogenerated documentation"

# Paths to complete yaml files used as few-shot style examples
FEW_SHOT_YAML_PATHS = [
    "src/offbeatLib/burnup/burnup.yaml",
    "src/offbeatLib/burnup/burnupFromPower.yaml",
    "src/offbeatLib/gapGasModel/gapFrapcon.yaml",
    "src/offbeatLib/heatSource/heatSource.yaml",
]

# Formulations shorter than this (chars) are candidates for extension
FORMULATION_EXTEND_MIN_CHARS = 300

# Delay between consecutive LLM API calls (generate/check)
API_RATE_DELAY = 0.3

# Retry parameters for 429 rate-limit errors
RETRY_MAX_ATTEMPTS = 5
RETRY_BASE_DELAY = 2.0   # seconds; doubles each attempt (exponential backoff)


# Custom yaml Dumper: multi-line strings use literal block style (|) so that
# LaTeX sequences like \sigma, \n etc. are never interpreted as YAML escapes.
class _LiteralDumper(yaml.Dumper):
    pass

def _literal_str_representer(dumper, data):
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)

_LiteralDumper.add_representer(str, _literal_str_representer)


def _yaml_dump(data: dict) -> str:
    return yaml.dump(data, Dumper=_LiteralDumper, allow_unicode=True,
                     default_flow_style=False, sort_keys=False, width=120)


# =============================================================================
# YAML schema documentation (injected into system prompts)
# =============================================================================

YAML_SCHEMA_DOC = """
The foamForNuclear yaml sidecar files follow this schema (all fields optional):

  description: |
    Multi-line description of the class. Supports:
      - Inline math:   $expression$ or \\f$expression\\f$
      - Display math:  $$...$$  or  \\f[...\\f]
      - Cross-refs:    [@ClassName]

  formulation: |
    Mathematical formulation section for classes implementing physical models.
    Same markup conventions as description. Explain governing equations,
    variables, and physical assumptions.

  admonitions:
    - kind: warning  # or: note | tip | important | caution
      body: |
        Text of the admonition.

  dictionary: neutronicsProperties   # optional: the input dictionary FILE the
                                      # options below are read from — i.e. the
                                      # file the user edits in their case (e.g.
                                      # neutronicsProperties, physicalProperties,
                                      # fvSolution). Rendered as a "Set in ..." note.

  optionsLocations:          # optional: named sub-dictionary locations
    - name: mySubDict
      in: solverDict

  options:
    - key: paramName
      type: scalar           # scalar | vector | word | bool | list[word] | table | ...
      location: mySubDict    # optional: sub-dictionary where key lives
      dictionary: nuclearData  # optional: overrides the class-level `dictionary`
                               # for THIS option only (when it is read from a
                               # different input file than the others)
      required: true         # true | false
      default: 1.0           # omit if no default
      description: |
        Description of the parameter.

  externalOptions:           # options read from non-standard files (e.g. 0/uniform/)
    - key: paramName
      path: <timeDirectory>.uniform.gapGas
      type: scalar
      required: true
      description: |
        Description.

  usage:
    - comment: |
        Human-readable comment before the snippet.
      snippet: |
        OpenFOAM dictionary snippet (no language fence).

Do NOT include the preliminary warning admonition in generated files.
"""


# =============================================================================
# OpenAI client
# =============================================================================

def get_client() -> OpenAI:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        print("Error: OPENAI_API_KEY environment variable not set.")
        sys.exit(1)
    return OpenAI(api_key=api_key)


def _call_with_retry(fn, *args, **kwargs):
    """
    Call fn(*args, **kwargs) with exponential backoff on 429 rate-limit errors.
    Raises on non-retryable errors or after RETRY_MAX_ATTEMPTS exhausted.
    """
    delay = RETRY_BASE_DELAY
    for attempt in range(1, RETRY_MAX_ATTEMPTS + 1):
        try:
            return fn(*args, **kwargs)
        except Exception as e:
            msg = str(e)
            is_rate_limit = "429" in msg or "Too Many Requests" in msg or "rate_limit" in msg.lower()
            if is_rate_limit and attempt < RETRY_MAX_ATTEMPTS:
                print(f"  [rate limit] waiting {delay:.0f}s before retry {attempt}/{RETRY_MAX_ATTEMPTS - 1}...")
                time.sleep(delay)
                delay *= 2
            else:
                raise


# =============================================================================
# File discovery
# =============================================================================

def find_all_yaml_files(repo_root: Path) -> list[Path]:
    """Return all yaml sidecar files in src/ and applications/, plus expected paths for
    classes that have both .H and .C but no yaml yet."""
    found: set[Path] = set()
    for search_dir in [repo_root / "src", repo_root / "applications"]:
        if not search_dir.exists():
            continue
        for p in search_dir.rglob("*.yaml"):
            if any(part in EXCLUDE_YAML_PARTS for part in p.parts):
                continue
            found.add(p)
        # Add expected yaml paths for concrete classes (.H + .C + class declaration)
        for h_path in search_dir.rglob("*.H"):
            if any(part in EXCLUDE_YAML_PARTS for part in h_path.parts):
                continue
            if not h_path.with_suffix(".C").exists():
                continue
            yaml_path = h_path.with_suffix(".yaml")
            if yaml_path in found:
                continue
            try:
                h_text = h_path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            if not re.search(r'^class\s+', h_text, re.MULTILINE):
                continue
            found.add(yaml_path)
    return sorted(found)


_PROGRESS_LINK_RE = re.compile(r'\[([^\]]+\.yaml)\]\(https?://[^)]+\)')


def load_progress_paths(repo_root: Path) -> frozenset[Path]:
    """Parse yaml_progress.md and return absolute paths of incomplete yaml files."""
    md_path = repo_root / "documentation" / "sphinx" / "cppapi" / "yaml_progress.md"
    if not md_path.exists():
        return frozenset()
    text = md_path.read_text(encoding="utf-8", errors="ignore")
    return frozenset(repo_root / m.group(1) for m in _PROGRESS_LINK_RE.finditer(text))


def is_incomplete(yaml_path: Path, progress_paths: frozenset = frozenset()) -> bool:
    """True if the yaml file needs generation or improvement.

    Triggers on any of:
      - file does not exist
      - file is blank / unparseable
      - file contains the INCOMPLETE_MARKER admonition
      - file is listed in yaml_progress.md AND has no ai_provenance yet
      - file has no usage examples AND has never been AI-processed
    """
    if not yaml_path.exists():
        return True
    try:
        content = yaml_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return True
    if not content.strip():
        return True
    if INCOMPLETE_MARKER in content:
        return True
    try:
        data = yaml.safe_load(content) or {}
    except Exception:
        data = {}
    has_provenance = bool(data.get("ai_provenance"))
    # Progress file lists files that still need work; skip if AI already processed it
    if yaml_path in progress_paths and not has_provenance:
        return True
    # No usage examples and never AI-processed → still needs generation
    if not data.get("usage") and not has_provenance:
        return True
    return False


def find_all_guide_files(repo_root: Path) -> list[Path]:
    """Return all RST and Markdown files in documentation/sphinx/usersguide/,
    excluding index files."""
    guide_dir = repo_root / "documentation" / "sphinx" / "usersguide"
    if not guide_dir.exists():
        return []
    return sorted(
        p for p in guide_dir.rglob("*")
        if p.suffix in (".rst", ".md") and p.stem != "index"
    )


_LEFTOVER_FLAG_RE = re.compile(r'[ \t]*toctreehere[ \t]*\r?\n?$', re.IGNORECASE)


def _strip_leftover_flags(text: str) -> str:
    """Remove standalone 'toctreeHere' placeholder lines (leftovers from an old
    doc workflow that now render as literal text), dropping one adjacent blank
    line so no double gap is left. Preserves the file's newline style."""
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    i = 0
    while i < len(lines):
        if _LEFTOVER_FLAG_RE.fullmatch(lines[i]):
            i += 1
            if i < len(lines) and lines[i].strip() == "":
                i += 1  # also consume one trailing blank line
            continue
        out.append(lines[i])
        i += 1
    return "".join(out)


def _is_skeleton_page(text: str) -> bool:
    """True if a guide page is essentially just a title + toctree (+ anchors/
    spacers) with no real prose — a candidate for an AI-generated introduction.
    """
    in_directive = False
    directive_indent = 0
    prose_words = 0
    for raw in text.splitlines():
        ln = raw.rstrip("\r\n")
        s = ln.strip()
        if not s:
            in_directive = False
            continue
        if re.match(r'^\.\. _[\w./-]+:\s*$', s):          # RST anchor
            continue
        if re.match(r'^\([\w.-]+\)=\s*$', s):              # MyST target
            continue
        if re.match(r'^\.\. [\w-]+::', s) or re.match(r'^(?:`{3,}|:{3,})\{[\w-]+\}', s):
            in_directive = True
            directive_indent = len(ln) - len(ln.lstrip())
            continue
        indent = len(ln) - len(ln.lstrip())
        if in_directive and indent > directive_indent:     # directive body/options
            continue
        if re.match(r'^:[\w-]+:', s):                      # stray directive option
            continue
        if re.fullmatch(r'[=\-~^"#*+.`\']{3,}', s):        # heading underline/overline
            continue
        if re.fullmatch(r'(?:`{3,}|:{3,}|<[^>]+>)', s):    # fence close / raw html
            continue
        in_directive = False
        prose_words += len(s.lstrip('# ').split())         # MD heading hashes stripped
    # Only the title's own words should remain on a skeleton page.
    return prose_words <= 8


def find_skeleton_index_files(repo_root: Path) -> list[Path]:
    """Return usersguide index pages that are just a title + toctree (no prose)."""
    guide_dir = repo_root / "documentation" / "sphinx" / "usersguide"
    if not guide_dir.exists():
        return []
    out: list[Path] = []
    for p in sorted(guide_dir.rglob("*")):
        if p.suffix not in (".rst", ".md") or p.stem != "index":
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if (".. toctree::" in text or "{toctree}" in text) and _is_skeleton_page(text):
            out.append(p)
    return out


def _rst_structural_elements(text: str) -> set[str]:
    """
    Extract RST anchors, directive names, and toctree entry paths.
    Used to validate that the LLM hasn't dropped structural content.
    """
    import re
    # Cross-reference labels:  .. _some-label:
    anchors = set(re.findall(r"\.\. _[\w./-]+:", text))
    # Directive names (no trailing space required — catches '.. toctree::' alone on a line)
    directives = set(re.findall(r"\.\. (\w[\w-]*)::[ \t\n]", text))
    # Toctree entry paths (lines indented inside a toctree block)
    toctree_entries = set(re.findall(r"^\s+(?:[^<\n]+<)?((?:\.\./)+[\w./]+)>?\s*$", text, re.MULTILINE))
    return anchors | directives | toctree_entries


def _md_structural_elements(text: str) -> set[str]:
    """
    Extract MyST/Markdown heading anchors, explicit targets, and directive names.
    Used to validate that the LLM hasn't dropped structural content.
    """
    # Heading attribute anchors:  {#some-anchor}
    anchors = set(re.findall(r"\{#[\w.-]+\}", text))
    # Explicit MyST targets:  (some-target)=
    targets = set(re.findall(r"^\([\w.-]+\)=\s*$", text, re.MULTILINE))
    # Fenced/colon directives:  ```{name}  or  :::{name}
    directives = set(re.findall(r"^(?:`{3,}|:{3,})\{(\w[\w-]*)\}", text, re.MULTILINE))
    return anchors | targets | directives


def polish_guide_file(
    client: OpenAI,
    rst_path: Path,
    model: str,
    cache: dict,
    dry_run: bool,
    verbose: bool,
    output_dir: Path | None = None,
) -> dict:
    """Improve English and formatting of a single usersguide file (RST or Markdown)."""
    result: dict = {"path": str(rst_path), "action": "none"}

    is_md = rst_path.suffix == ".md"
    system_prompt = _SYSTEM_GUIDE_POLISHER_MD if is_md else _SYSTEM_GUIDE_POLISHER
    fmt_label = "Markdown (MyST)" if is_md else "RST"
    elements_of = _md_structural_elements if is_md else _rst_structural_elements

    original = rst_path.read_text(encoding="utf-8")

    # Never send empty/near-empty files to the LLM: it has nothing to polish
    # and tends to reply conversationally, which would be saved as content.
    if len(original.strip()) < 40:
        result["from_cache"] = False
        return result

    content_hash = hashlib.md5(original.encode()).hexdigest()[:8]
    cache_key = f"guide|{rst_path}|{model}|{content_hash}"

    result["from_cache"] = cache_key in cache

    if cache_key in cache:
        improved = cache[cache_key]
    else:
        user_prompt = f"Improve the following {fmt_label} file:\n\n{original}"
        improved = _call_with_retry(
            _chat, client, model, system_prompt, user_prompt, 0.2,
            max(4096, len(original) // 3),
        )
        # Strip accidental fences
        if improved.startswith("```"):
            improved = improved.split("\n", 1)[1] if "\n" in improved else improved
            if improved.endswith("```"):
                improved = improved[:-3].rstrip()

    # Remove leftover 'toctreeHere' placeholder lines regardless of what the LLM
    # did, so a file whose only needed change is that removal still gets written.
    improved = _strip_leftover_flags(improved)

    # Validate structural elements are preserved
    orig_elements = elements_of(original)
    new_elements = elements_of(improved)
    missing = orig_elements - new_elements
    if missing:
        result["error"] = f"LLM dropped structural elements: {', '.join(sorted(missing))}"
        if verbose:
            print(f"    SKIP — missing elements: {', '.join(sorted(missing))}")
        return result

    if improved == original:
        result["action"] = "none"
        cache[cache_key] = improved
        return result

    result["action"] = "polished"
    result["new_content"] = improved
    result["original"] = original
    cache[cache_key] = improved

    if not dry_run:
        _resolve_output_path(rst_path, output_dir).write_text(improved, encoding="utf-8")

    return result


def _toctree_entries(text: str) -> list[str]:
    """Return the document paths listed inside a page's toctree block(s)
    (both RST ``.. toctree::`` and MyST ```` ```{toctree} ````)."""
    entries: list[str] = []
    in_toctree = False
    for raw in text.splitlines():
        s = raw.strip()
        if re.match(r'^\.\. toctree::', s) or re.match(r'^(?:`{3,}|:{3,})\{toctree\}', s):
            in_toctree = True
            continue
        if not in_toctree:
            continue
        if not s:
            continue
        if s.startswith(":"):                       # directive option (:maxdepth: ...)
            continue
        if re.match(r'^\.\. ', s) or re.match(r'^(?:`{3,}|:{3,})', s):
            in_toctree = False                       # next directive / fence close
            continue
        m = re.match(r'^(?:[^<]*<)?([^>]+)>?$', s)    # 'Title <path>' or bare 'path'
        if m:
            entries.append(m.group(1).strip())
    return entries


def _page_title(path: Path) -> str:
    """Best-effort first heading of an RST/MD page (for child-section context)."""
    try:
        lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
    except OSError:
        return path.stem
    for i, raw in enumerate(lines):
        s = raw.strip()
        if not s or re.match(r'^\.\. ', s) or re.match(r'^\([\w.-]+\)=', s):
            continue
        if s.startswith("#"):                                    # Markdown heading
            return s.lstrip("# ").strip()
        if i + 1 < len(lines) and re.fullmatch(r'[=\-~^"#*+.`\']{3,}', lines[i + 1].strip()):
            return s                                             # RST title + underline
    return path.stem


def generate_index_intro(
    client: OpenAI,
    rst_path: Path,
    model: str,
    cache: dict,
    dry_run: bool,
    output_dir: Path | None = None,
) -> dict:
    """Generate a short introduction for a skeleton index page (title + toctree,
    no prose) and insert it between the title and the toctree. Writes to the AI
    content tree; the original (standard build) keeps its bare index."""
    result: dict = {"path": str(rst_path), "action": "none"}
    original = rst_path.read_text(encoding="utf-8")
    is_md = rst_path.suffix == ".md"

    title = _page_title(rst_path)
    child_titles = []
    for entry in _toctree_entries(original):
        cand = (rst_path.parent / entry)
        for suffix in (".rst", ".md"):
            f = cand.with_suffix(suffix)
            if f.exists():
                child_titles.append(_page_title(f))
                break
        else:
            child_titles.append(entry.rsplit("/", 1)[-1])

    content_hash = hashlib.md5(original.encode()).hexdigest()[:8]
    cache_key = f"guide-intro|{rst_path}|{model}|{content_hash}"
    result["from_cache"] = cache_key in cache

    if cache_key in cache:
        intro = cache[cache_key]
    else:
        children = "\n".join(f"- {t}" for t in child_titles) or "(none listed)"
        fmt = "Markdown (MyST)" if is_md else "reStructuredText"
        user_prompt = (
            f"Write a short introduction (2-4 sentences, one paragraph) for the "
            f"foamForNuclear user-guide section titled \"{title}\". The section "
            f"groups these subsections:\n{children}\n\n"
            f"Explain in plain {fmt} prose what this section covers and how the "
            f"subsections fit together, for graduate students in nuclear "
            f"engineering. Output ONLY the paragraph text: no heading, no title, "
            f"no toctree, no lists, no markup fences."
        )
        intro = _call_with_retry(
            _chat, client, model, _SYSTEM_GUIDE_INTRO, user_prompt, 0.3, 600
        ).strip()
        if intro.startswith("```"):
            intro = intro.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
        cache[cache_key] = intro

    if not intro:
        return result

    newline = "\r\n" if "\r\n" in original else "\n"
    lines = original.split(newline)
    # Insert the intro just before the first toctree directive.
    insert_at = next(
        (i for i, ln in enumerate(lines)
         if re.match(r'^\s*\.\. toctree::', ln)
         or re.match(r'^\s*(?:`{3,}|:{3,})\{toctree\}', ln)),
        None,
    )
    if insert_at is None:
        return result
    block = intro.split("\n")
    new_lines = lines[:insert_at] + block + [""] + lines[insert_at:]
    new_content = newline.join(new_lines)

    if new_content == original:
        return result
    result["action"] = "intro-added"
    result["new_content"] = new_content
    result["original"] = original
    if not dry_run:
        _resolve_output_path(rst_path, output_dir).write_text(new_content, encoding="utf-8")
    return result


_tutorial_files_cache: list | None = None

def _get_tutorial_files(repo_root: Path) -> list:
    """Return sorted list of tutorial files, cached after the first call."""
    global _tutorial_files_cache
    if _tutorial_files_cache is None:
        tutorials_dir = repo_root / "tutorials"
        if not tutorials_dir.exists():
            _tutorial_files_cache = []
        else:
            _tutorial_files_cache = sorted(
                f for f in tutorials_dir.rglob("*") if f.is_file()
            )
    return _tutorial_files_cache


def find_tutorial_usage(class_name: str, repo_root: Path, max_snippets: int = 3) -> list[str]:
    """
    Search tutorial files for actual usage of class_name.

    Recognises two OpenFOAM patterns:
      1. ``type ClassName;``  — concrete class selected at runtime
      2. ``ClassName { ... }``  — abstract registry key (e.g. saturationModel)
    Returns a list of annotated code snippets (up to max_snippets).
    """
    import re
    tutorials_dir = repo_root / "tutorials"
    if not tutorials_dir.exists():
        return []

    # Pattern 1: runtime selection  →  type saturationModel;
    type_pattern = re.compile(rf'\btype\s+{re.escape(class_name)}\b')
    # Pattern 2: sub-dict registry key  →  saturationModel\n{   or   saturationModel {
    dict_pattern = re.compile(rf'^\s*{re.escape(class_name)}\s*(\{{|$)', re.MULTILINE)

    snippets: list[str] = []

    def _extract_block(lines: list[str], match_line: int) -> str:
        """Return the enclosing OpenFOAM dict block around match_line, capped at 30 lines."""
        # Walk backwards to find the enclosing sub-dictionary opening
        depth = 0
        open_line = match_line
        for j in range(match_line - 1, max(-1, match_line - 30), -1):
            depth += lines[j].count('}') - lines[j].count('{')
            if depth < 0:
                open_line = max(0, j - 1)
                break
        # Walk forward to find the closing brace
        depth = 0
        close_line = match_line
        for j in range(open_line, min(len(lines), match_line + 40)):
            depth += lines[j].count('{') - lines[j].count('}')
            if depth <= 0 and j > open_line:
                close_line = j
                break
        block = "\n".join(lines[open_line:close_line + 1]).strip()
        block_lines = block.splitlines()
        if len(block_lines) > 30:
            block = "\n".join(block_lines[:30]) + "\n    // ..."
        return block

    seen_blocks: set[str] = set()

    for f in _get_tutorial_files(repo_root):
        try:
            text = f.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue

        # Skip binary-looking files quickly
        if '\x00' in text[:512]:
            continue

        lines = text.splitlines()
        matched_line: int | None = None

        # Check pattern 1 first
        if type_pattern.search(text):
            for i, line in enumerate(lines):
                if type_pattern.search(line):
                    matched_line = i
                    break

        # Fall back to pattern 2 (sub-dict key)
        if matched_line is None and dict_pattern.search(text):
            for i, line in enumerate(lines):
                if re.match(rf'^\s*{re.escape(class_name)}\s*(\{{|$)', line):
                    matched_line = i
                    break

        if matched_line is None:
            continue

        block = _extract_block(lines, matched_line)
        if block in seen_blocks:
            continue
        seen_blocks.add(block)

        rel = f.relative_to(repo_root)
        snippets.append(f"// From {rel}:\n{block}")

        if len(snippets) >= max_snippets:
            break

    return snippets


def find_source_files(yaml_path: Path) -> dict:
    """
    Find C++ source files (.H and .C) adjacent to a yaml sidecar.
    Returns a dict with keys 'class_name', optionally 'header' and 'implementation'.
    """
    class_name = yaml_path.stem
    parent = yaml_path.parent
    info: dict = {"class_name": class_name}

    h_path = parent / f"{class_name}.H"
    c_path = parent / f"{class_name}.C"

    if h_path.exists():
        info["header"] = h_path.read_text(encoding="utf-8", errors="ignore")
    if c_path.exists():
        info["implementation"] = c_path.read_text(encoding="utf-8", errors="ignore")

    return info


# =============================================================================
# Context building
# =============================================================================

def load_few_shot_examples(repo_root: Path) -> str:
    """Concatenate complete yaml examples to use as style reference."""
    parts = []
    for rel in FEW_SHOT_YAML_PATHS:
        p = repo_root / rel
        if p.exists():
            parts.append(f"# Example: {rel}\n{p.read_text(encoding='utf-8')}")
    return "\n\n---\n\n".join(parts)


def load_sphinx_index(repo_root: Path) -> str:
    """Load the sphinx index.rst to give the LLM project structure context."""
    idx = repo_root / "documentation" / "sphinx" / "cppapi" / "index.rst"
    if idx.exists():
        return idx.read_text(encoding="utf-8")[:4000]
    return ""


# Dictionary-access patterns: where OpenFOAM code reads run-time options
# (dict.lookup(), get<T>(), getOrDefault<>(), readScalar(), subDict(), found(), ...).
_DICT_READ_RE = re.compile(
    r'\b(?:lookup\w*|get(?:OrDefault)?|read(?:Scalar|Label|Bool|Word|Entry|IfPresent)\w*'
    r'|sub(?:Dict|OrEmptyDict)|found|isDict)\s*[<(]'
)

# Dictionary-definition patterns: where the input FILE a class reads from is
# named — e.g. IOobject("neutronicsProperties", ...), IOdictionary construction.
# These sites usually live in the constructor, away from the lookup calls, so
# the `dictionary` field would be missed if only read sites were surfaced.
# The (?!::) guard skips scope-resolution uses like IOobject::READ_IF_PRESENT,
# which otherwise match on nearly every constructor line and chain the windows
# into one giant block.
_DICT_DEFINE_RE = re.compile(r'\b(?:IO(?:object|dictionary)|regIOobject)\b(?!::)')


def _read_aware_excerpt(text: str, budget: int, context_lines: int = 6,
                        head_lines: int = 30) -> str:
    """
    Return an excerpt of ``text`` no longer than ``budget`` characters that
    preferentially includes the regions where the code reads from input
    dictionaries (option discovery) and where it names the dictionary FILE it
    reads from (the `dictionary` field), so both work even when those sites sit
    deep in a long .C file. A plain head slice silently misses constructors that
    appear after a lot of preamble (license, includes, static members). Elided
    spans are marked with a comment. Text already within budget — or with no
    detectable dictionary sites — is returned as a normal head slice.
    """
    if len(text) <= budget:
        return text

    lines = text.splitlines()
    n = len(lines)
    read_lines = [i for i, ln in enumerate(lines) if _DICT_READ_RE.search(ln)]
    define_lines = [i for i, ln in enumerate(lines) if _DICT_DEFINE_RE.search(ln)]
    if not read_lines and not define_lines:
        return text[:budget]

    cost = [len(ln) + 1 for ln in lines]  # +1 for the newline

    def _merge(intervals):
        out: list[list[int]] = []
        for lo, hi in sorted(intervals):
            if out and lo <= out[-1][1]:
                out[-1][1] = max(out[-1][1], hi)
            else:
                out.append([lo, hi])
        return [(lo, hi) for lo, hi in out]

    def _windows(line_idxs, ctx):
        return _merge(
            (max(0, i - ctx), min(n, i + ctx + 1)) for i in line_idxs
        )

    # Reads get a generous window (need surrounding logic to infer type/default);
    # define sites get a tight one so the file-name string is not buried in a big
    # merged block of consecutive field-registration IOobjects.
    read_wins = _windows(read_lines, context_lines)
    define_wins = _windows(define_lines, 4)
    head_win = (0, min(head_lines, n))

    selected: list[tuple[int, int]] = []
    used = 0

    def _take(windows, cap):
        """Add windows in file order while staying under ``cap`` total chars. A
        window larger than the remaining room is truncated to its leading lines
        rather than dropped, so a single dense read-region still fills the budget
        instead of leaving the excerpt nearly empty."""
        nonlocal used
        for lo, hi in windows:
            if (lo, hi) in selected:
                continue
            if used + sum(cost[lo:hi]) <= cap:
                selected.append((lo, hi))
                used += sum(cost[lo:hi])
                continue
            end, acc = lo, 0
            while end < hi and used + acc + cost[end] <= cap:
                acc += cost[end]
                end += 1
            if end > lo:
                selected.append((lo, end))
                used += acc

    # Reserve a small slice for the earliest dictionary-name site(s) so the
    # `dictionary` field is discoverable even on read-heavy files, then spend the
    # bulk on option reads (the primary signal), then backfill remaining
    # define sites and the head for class context.
    _take(define_wins, min(used + max(budget // 5, 600), budget))
    _take(read_wins, budget)
    _take(define_wins + [head_win], budget)

    if not selected:
        return text[:budget]

    parts: list[str] = []
    prev_hi = 0
    for lo, hi in _merge(selected):
        if lo > prev_hi:
            parts.append(f"// ... [{lo - prev_hi} line(s) omitted] ...")
        parts.extend(lines[lo:hi])
        prev_hi = hi
    if prev_hi < n:
        parts.append(f"// ... [{n - prev_hi} line(s) omitted] ...")
    return "\n".join(parts)


# Optional global override for the per-file source-context budget (chars),
# set from the CLI (--source-budget / --full-source). It can only RAISE a
# call site's budget, never lower it, so the read-aware excerpting still
# applies the same priorities — there is just more room. A very large value
# effectively sends whole files. None = use each call site's default.
SOURCE_BUDGET_OVERRIDE: int | None = None


def build_source_context(source_info: dict, max_header: int = 8000, max_impl: int = 4000) -> str:
    """Format source files as a context string for LLM prompts."""
    if SOURCE_BUDGET_OVERRIDE is not None:
        max_header = max(max_header, SOURCE_BUDGET_OVERRIDE)
        max_impl = max(max_impl, SOURCE_BUDGET_OVERRIDE)
    name = source_info["class_name"]
    ctx = ""
    if "header" in source_info:
        hdr = _read_aware_excerpt(source_info["header"], max_header)
        ctx += f"\n### {name}.H\n```cpp\n{hdr}\n```"
    if "implementation" in source_info:
        impl = _read_aware_excerpt(source_info["implementation"], max_impl)
        ctx += f"\n### {name}.C\n```cpp\n{impl}\n```"
    return ctx


# =============================================================================
# System prompts
# =============================================================================

_SYSTEM_CODE_ANALYST = f"""You are an expert in OpenFOAM C++ code analysis and nuclear engineering simulation.
The foamForNuclear project is a multi-physics nuclear reactor simulation framework built on OpenFOAM,
implementing neutronics, thermal-hydraulics, fuel performance, and thermo-mechanics solvers.

Your task is to analyze C++ source code and produce accurate yaml documentation sidecars.
{YAML_SCHEMA_DOC}
Rules:
- Extract `options` by reading how the code calls dict.get<T>(), dict.lookup(), or similar.
- Never fabricate options that do not appear in the source code.
- Set the class-level `dictionary` to the input FILE the options are read from
  — the file the user edits in their case. Infer it from the name the lookups
  run against: an IOdictionary/IOobject constructed with the name
  "neutronicsProperties" (or a member dict read from that file) means
  `dictionary: neutronicsProperties`. If a particular option is clearly read
  from a DIFFERENT file (e.g. looked up from "nuclearData"), set that option's
  `dictionary` override instead of the class-level one. Only set `dictionary`
  when the file name is visible in the source — never guess a file name.
- For the `usage` field: use ONLY the tutorial examples provided in the prompt.
  If no tutorial examples are provided, set `usage: []`. Never invent usage snippets.
- Return only the yaml content (no markdown fences, no preamble, no explanation).

Passive content check (while you read the source):
- If the source code contains offensive, hateful, or unprofessional language in comments
  (slurs, insults, harassment — NOT normal technical jargon or engineering shorthand),
  prepend exactly one line before the yaml: FLAGGED: <brief reason>
- Otherwise do not mention this at all.
"""

_SYSTEM_THEORY_WRITER = """You are an expert in nuclear engineering, reactor physics, and computational simulation.
Your formulation sections target graduate students in nuclear engineering (MSc/PhD level).

Guidelines for the `formulation` field:
- State the physical model in one or two clear sentences before equations.
- Write governing equations in LaTeX using display math: $$ ... $$
- Define every variable below the equation with a dash-list: - $x$ is the ...
- Reference standard texts (Duderstadt & Hamilton, Todreas & Kazimi, etc.) where appropriate.
- Use OpenFOAM field-name conventions where relevant ($T$, $Q$, $\\rho$, etc.).
- Be concise: a formulation section should fit in 10–25 lines.

STRICT MARKUP RULES (the text is rendered as reStructuredText + MathJax):
- Put $$ delimiters on their OWN lines, with the equation between them.
- No whitespace just inside inline math: write $\\alpha$, never $ \\alpha $.
- NEVER use LaTeX text commands (\\texttt, \\textbf, \\textit) — this is not a
  LaTeX document. Code identifiers, keywords, and C++ names go in RST
  double-backticks (``momentumSource``), in prose only — never inside math.
- Multi-character identifiers must not appear inside math: use a short symbol
  in the equation and state which input parameter sets it, e.g.
  $f(t)$ ... where $f(t)$ is set by ``momentumSourceTimeProfile``.
- Leave a blank line between a paragraph and a following dash-list.
"""

_SYSTEM_GUIDE_POLISHER = """You are a technical writer improving documentation for foamForNuclear,
a multi-physics nuclear reactor simulation framework built on OpenFOAM.
The audience is graduate students in nuclear engineering (MSc/PhD level).

Your task: improve the English clarity and formatting of the RST file you receive.

WHAT TO IMPROVE:
- Fix grammar, spelling, and awkward phrasing.
- Improve sentence flow and clarity without changing meaning.
- Make capitalization and list punctuation consistent.
- Break overly long sentences into shorter ones.
- Ensure consistent use of Oxford comma, active voice where natural.

WHAT YOU MUST NEVER CHANGE:
- RST cross-reference labels (``.. _some-label:``) — keep them in their EXACT original position.
  Never move a label, reorder them, or place them after the section heading they precede.
- RST roles:  :ref:`, :class:`, :func:`, :doc:`, :math:`
- RST directives and their options:  .. code-block::, .. math::, .. toctree::, .. figure::, .. note::, etc.
- toctree entries — every entry that exists in the original must appear in the output, in the SAME order.
- Content inside code blocks (.. code-block:: sections) — leave verbatim.
- Content inside math blocks (.. math:: sections) — leave verbatim.
- URLs, file paths, class names, option names, and OpenFOAM dictionary keys.
- Section heading underline/overline characters and their length (must match title length exactly).
- The file's overall section structure and order — do not add, remove, or reorder sections.

Return ONLY the complete improved RST file with no preamble, explanation, or markdown fences."""

_SYSTEM_GUIDE_POLISHER_MD = """You are a technical writer improving documentation for foamForNuclear,
a multi-physics nuclear reactor simulation framework built on OpenFOAM.
The audience is graduate students in nuclear engineering (MSc/PhD level).

Your task: improve the English clarity and formatting of the Markdown (MyST) file you receive.

WHAT TO IMPROVE:
- Fix grammar, spelling, and awkward phrasing.
- Improve sentence flow and clarity without changing meaning.
- Make capitalization and list punctuation consistent.
- Break overly long sentences into shorter ones.
- Ensure consistent use of Oxford comma, active voice where natural.

WHAT YOU MUST NEVER CHANGE:
- The output MUST remain Markdown. NEVER convert to reStructuredText:
  no ``.. directive::`` blocks, no ``====``/``----`` heading underlines, no ``:ref:`` roles.
- Heading levels (number of leading #) and the overall section structure and
  order — do not add, remove, or reorder sections.
- Heading anchors (``{#some-anchor}``) and MyST targets (``(some-target)=``) —
  keep them attached to their original headings.
- MyST directives (e.g. ```{note}, ```{toctree}, :::{warning}) and their options.
- Content inside code fences (``` blocks) — leave verbatim.
- Inline code spans, URLs, file paths, image references, class names, option
  names, and OpenFOAM dictionary keys.

Return ONLY the complete improved Markdown file with no preamble, explanation,
or enclosing code fence."""

_SYSTEM_GUIDE_INTRO = """You are a technical writer for foamForNuclear, a multi-physics nuclear
reactor simulation framework built on OpenFOAM. The audience is graduate
students in nuclear engineering (MSc/PhD level).

Your task: write a SHORT introduction for a user-guide section landing page that
currently has only a title and a table of contents. State what the section
covers and how its subsections relate, so a reader knows what to expect.

STRICT RULES:
- Output ONLY the introduction prose — no heading, no title, no underline, no
  toctree, no bullet list, no code fence, no preamble.
- 2-4 sentences, a single paragraph. Be concrete and factual; do not invent
  features, file names, or capabilities not implied by the subsection titles.
- Plain prose in the requested markup language. Keep any OpenFOAM/dictionary
  names in the correct inline-code markup if you mention them."""


# =============================================================================
# LLM helpers
# =============================================================================

def _strip_fences(text: str) -> str:
    """Remove leading/trailing markdown code fences that LLMs sometimes add."""
    text = text.strip()
    if text.startswith("```yaml"):
        text = text[7:]
    elif text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    return text.strip()


def _extract_flag(raw: str) -> tuple[str | None, str]:
    """
    If the LLM prepended 'FLAGGED: <reason>' before the yaml, extract it.
    Returns (reason_or_None, clean_yaml_text).
    """
    first_line, sep, rest = raw.partition("\n")
    if first_line.startswith("FLAGGED:"):
        return first_line[len("FLAGGED:"):].strip(), rest.strip()
    return None, raw


# Which token-limit kwarg the installed openai client accepts. Newer libraries/
# models use `max_completion_tokens`; older ones only know `max_tokens`. Detected
# once on the first call and reused.
_MAX_TOKENS_PARAM: str | None = None


def _chat(client: OpenAI, model: str, system: str, user: str, temperature: float = 0.3,
          max_tokens: int = 4096) -> str:
    global _MAX_TOKENS_PARAM
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]

    def _create(param: str):
        return _call_with_retry(
            client.chat.completions.create,
            model=model,
            messages=messages,
            temperature=temperature,
            **{param: max_tokens},
        )

    if _MAX_TOKENS_PARAM is None:
        try:
            response = _create("max_completion_tokens")
            _MAX_TOKENS_PARAM = "max_completion_tokens"
        except TypeError as exc:
            if "max_completion_tokens" not in str(exc):
                raise
            response = _create("max_tokens")
            _MAX_TOKENS_PARAM = "max_tokens"
    else:
        response = _create(_MAX_TOKENS_PARAM)

    return response.choices[0].message.content.strip()


# =============================================================================
# Core generation functions
# =============================================================================

def generate_yaml(
    client: OpenAI,
    yaml_path: Path,
    source_info: dict,
    existing_yaml: str,
    few_shot: str,
    model: str,
    theory_model: str,
    add_theory: bool,
    cache: dict,
    tutorial_snippets: list[str] | None = None,
) -> str:
    """
    Generate a complete yaml for an incomplete file.
    Uses source code + few-shot examples as context.
    If add_theory, uses theory_model for the formulation section.
    tutorial_snippets: real usage examples found in tutorials/ for the usage field.
    """
    class_name = source_info["class_name"]
    src_ctx = build_source_context(source_info)

    # Key includes a hash of stub + source so changed code invalidates the cache
    ctx_hash = hashlib.md5((existing_yaml + src_ctx).encode()).hexdigest()[:8]
    cache_key = f"generate_v2|{yaml_path}|{model}|{theory_model}|{add_theory}|{ctx_hash}"
    if cache_key in cache:
        return cache[cache_key]

    tutorial_ctx = ""
    if tutorial_snippets:
        tutorial_ctx = "\n\n## Tutorial usage examples (use these verbatim for the `usage` field):\n"
        tutorial_ctx += "\n\n".join(tutorial_snippets)
    else:
        try:
            _stub_usage = (yaml.safe_load(existing_yaml) or {}).get("usage")
        except Exception:
            _stub_usage = None
        if _stub_usage:
            tutorial_ctx = (
                "\n\n## Usage: the stub already contains usage examples. "
                "Copy the `usage` field verbatim into the output — do not modify or remove it."
            )
        else:
            tutorial_ctx = "\n\n## Tutorial usage: none found — set `usage: []` in the yaml."

    # --- Step 1: code analysis → structured yaml (without formulation) ---
    user_prompt_code = f"""Generate a complete yaml documentation file for the C++ class `{class_name}`.

## Source code:{src_ctx if src_ctx else "\n(No adjacent .H/.C files found — infer from class name and yaml stub.)"}

## Current stub (improve this, remove the warning admonition):
```yaml
{existing_yaml}
```

## Style examples (match this format exactly):
{few_shot[:3000]}
{tutorial_ctx}

Generate the yaml now. Return only the yaml content."""

    system = _SYSTEM_CODE_ANALYST
    if add_theory:
        system = _SYSTEM_CODE_ANALYST + "\n\n" + _SYSTEM_THEORY_WRITER

    raw_code = _chat(client, model, system, user_prompt_code, temperature=0.25)
    flag, raw_code = _extract_flag(raw_code)
    if flag:
        cache[f"source_flag|{yaml_path}"] = flag
    result = _strip_fences(raw_code)

    # --- Step 2: if separate theory model, regenerate only the formulation ---
    if add_theory and theory_model != model and src_ctx:
        # Parse result to check if formulation already good; otherwise enhance
        user_prompt_theory = f"""The following yaml documentation for `{class_name}` needs a high-quality
`formulation` section explaining the physical model mathematically.

## Source code for context:{src_ctx}

## Current yaml (add or improve the formulation field):
```yaml
{result}
```

Return the full corrected yaml with an improved `formulation` section.
Return only the yaml content."""

        result = _strip_fences(_chat(
            client, theory_model, _SYSTEM_THEORY_WRITER, user_prompt_theory, temperature=0.4
        ))

    cache[cache_key] = result
    return result


def _normalize_yaml_value(v):
    """Normalize parsed yaml for semantic comparison: drop None-valued dict
    entries (key absent vs key empty are equivalent) and trailing whitespace."""
    if isinstance(v, dict):
        return {k: _normalize_yaml_value(x) for k, x in v.items() if x is not None}
    if isinstance(v, list):
        return [_normalize_yaml_value(x) for x in v]
    if isinstance(v, str):
        return v.rstrip()
    return v


def _changed_sections(old_yaml: str, new_yaml: str) -> list[str]:
    """Return top-level yaml keys whose values SEMANTICALLY differ between old
    and new (re-serialization noise like dropped empty defaults is ignored)."""
    try:
        old = yaml.safe_load(old_yaml) or {}
        new = yaml.safe_load(new_yaml) or {}
        return [
            k for k in new
            if k not in ("ai_provenance",)
            and _normalize_yaml_value(old.get(k)) != _normalize_yaml_value(new.get(k))
        ]
    except Exception:
        return []


def _restore_dropped_options(orig: dict, new: dict) -> bool:
    """
    Restore options/externalOptions/optionsLocations that the LLM dropped from
    the original, matched by (key, location, path). The model only ever sees a
    truncated source excerpt, so "I did not find this option in the code" is
    not evidence of absence. Mutates ``new`` in place; returns True if anything
    was restored.
    """
    def _opt_id(o):
        return (o.get("key"), o.get("location"), o.get("path"))

    changed = False
    for field in ("options", "externalOptions"):
        orig_opts = [o for o in (orig.get(field) or []) if isinstance(o, dict)]
        new_opts = [o for o in (new.get(field) or []) if isinstance(o, dict)]
        new_ids = {_opt_id(o) for o in new_opts}
        dropped = [o for o in orig_opts if _opt_id(o) not in new_ids]
        if dropped:
            new[field] = new_opts + dropped
            changed = True

    if orig.get("optionsLocations") and not new.get("optionsLocations"):
        new["optionsLocations"] = orig["optionsLocations"]
        changed = True

    if orig.get("dictionary") and not new.get("dictionary"):
        new["dictionary"] = orig["dictionary"]
        changed = True

    return changed


def _preserve_human_content(existing_yaml: str, corrected: str) -> str:
    """
    Safety net after a consistency check: never let the LLM silently drop
    human-written content. Restores options/externalOptions removed from the
    original (matched by key+location), the original usage examples, and
    optionsLocations. The LLM only ever sees a truncated source excerpt, so
    "I did not find this option in the code" is not evidence of absence.
    """
    try:
        orig = yaml.safe_load(existing_yaml) or {}
        new = yaml.safe_load(corrected) or {}
        if not isinstance(orig, dict) or not isinstance(new, dict):
            return corrected
    except Exception:
        return corrected

    changed = _restore_dropped_options(orig, new)

    # usage is human-written and the prompt forbids touching it — enforce that
    if orig.get("usage") and \
            _normalize_yaml_value(new.get("usage")) != _normalize_yaml_value(orig.get("usage")):
        new["usage"] = orig["usage"]
        changed = True

    if changed:
        return _yaml_dump(new)
    return corrected


def _set_ai_provenance(yaml_str: str, model: str, **fields) -> str:
    """
    Insert or update the ai_provenance metadata block in a yaml string.
    Extra keyword arguments (generated, modified_sections, formulation_added, etc.)
    are merged into the block.
    """
    try:
        data = yaml.safe_load(yaml_str) or {}
    except Exception as exc:
        raise ValueError(f"LLM returned invalid yaml: {exc}\n---\n{yaml_str[:300]}") from exc
    prov = data.get("ai_provenance") or {}
    prov["model"] = model
    prov["date"] = date.today().isoformat()
    prov.update(fields)
    data["ai_provenance"] = prov
    return _yaml_dump(data)


def _extract_rst_toctrees(text: str) -> list[str]:
    """Return all ``.. toctree::`` blocks found in RST text (as raw strings)."""
    blocks = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        if re.match(r'^\s*\.\. toctree::', lines[i]):
            block_lines = [lines[i]]
            i += 1
            # Collect indented continuation lines (options and entries) plus
            # blank lines that appear before the next indented line.
            while i < len(lines):
                line = lines[i]
                if line.strip() == "":
                    block_lines.append(line)
                    i += 1
                elif re.match(r'^\s+', line):
                    block_lines.append(line)
                    i += 1
                else:
                    break
            # Strip trailing blank lines from the block
            while block_lines and block_lines[-1].strip() == "":
                block_lines.pop()
            blocks.append("\n".join(block_lines))
        else:
            i += 1
    return blocks


def _preserve_description_toctrees(orig_desc: str, new_desc: str) -> str:
    """
    If the original description contained ``.. toctree::`` blocks that are
    absent from the new description, append them at the end.
    """
    orig_blocks = _extract_rst_toctrees(orig_desc)
    if not orig_blocks:
        return new_desc
    new_blocks = _extract_rst_toctrees(new_desc)
    missing = [b for b in orig_blocks if b not in new_blocks]
    if not missing:
        return new_desc
    return new_desc.rstrip() + "\n\n" + "\n\n".join(missing)


def _merge_yaml_update(existing_yaml: str, partial_yaml: str) -> str:
    """
    Merge LLM-returned yaml into the existing yaml.
    Top-level keys present in partial_yaml overwrite those in existing_yaml.
    Keys absent from partial_yaml are preserved unchanged.
    Falls back to partial_yaml as-is if parsing fails.
    """
    try:
        base = yaml.safe_load(existing_yaml) or {}
        patch = yaml.safe_load(partial_yaml) or {}
        if isinstance(base, dict) and isinstance(patch, dict):
            merged = {**base, **patch}
            return _yaml_dump(merged)
    except Exception:
        pass
    return partial_yaml


def check_consistency(
    client: OpenAI,
    yaml_path: Path,
    source_info: dict,
    existing_yaml: str,
    model: str,
    cache: dict,
) -> tuple[bool, str]:
    """
    Check an existing (complete) yaml against its source code.
    Returns (needs_update, corrected_yaml_or_original).
    Cache key uses v3 suffix (v2 entries predate the human-content guard,
    formatting fixes, and larger source context).
    """
    content_hash = hashlib.md5(existing_yaml.encode()).hexdigest()[:8]
    cache_key = f"check_v4|{yaml_path}|{model}|{content_hash}"
    if cache_key in cache:
        cached = cache[cache_key]
        return cached["needs_update"], cached["yaml"]

    src_ctx = build_source_context(source_info, max_header=12000, max_impl=12000)
    if not src_ctx:
        return False, existing_yaml

    user_prompt = f"""Check whether the yaml documentation for `{source_info['class_name']}` is consistent
with its source code, and whether its markup is well-formed. Focus on:
1. Do the `options` match what the code reads from input dictionaries?
2. Is the class-level `dictionary` (the input FILE the options are read from)
   set and correct? Add it if the source clearly names the file the lookups run
   against (e.g. an IOdictionary/IOobject named "neutronicsProperties"). If an
   option is read from a different file, set that option's `dictionary`
   override. Never guess a file name that is not visible in the source.
3. Is the `description` accurate?
4. Is the markup correct? Fix formatting problems, in particular:
   - Multi-character parameter/keyword names must NEVER appear inside math
     markup (:math:`...`, $...$, \\f$...\\f$): LaTeX typesets them as a product
     of single-letter variables, which renders as garbage. Rewrite such
     expressions using short mathematical symbols, then state which input
     parameter sets each symbol, with parameter names in ``backticks``.
     BAD:
       :math:`turbulenceIntensityCoeff*Reynolds^{{turbulenceIntensityExp}}`
     GOOD:
       :math:`C \\, Re^{{\\,n}}`, where :math:`C` and :math:`n` are set by the
       ``turbulenceIntensityCoeff`` and ``turbulenceIntensityExp`` parameters
   - Malformed or unbalanced markup, and stray operators (**, ^) in prose.

## Source code (NOTE: possibly truncated — absence from this excerpt is NOT
evidence that an option does not exist):{src_ctx}

## Current yaml:
```yaml
{existing_yaml}
```

If everything is consistent and well-formatted, respond with exactly the word: CONSISTENT

Otherwise return the COMPLETE corrected yaml file (all fields, no fences,
no explanation). Preserve every field that is correct.

STRICT RULES:
- NEVER remove an existing option. You may correct its type, default, or
  description, or add missing options — but removal is forbidden (the source
  excerpt may be truncated; a human wrote these entries).
- Do NOT modify the `usage` field under any circumstances — it contains
  human-written examples.
- Do NOT rewrite text that is already correct merely to rephrase it."""

    raw = _chat(client, model, _SYSTEM_CODE_ANALYST, user_prompt, temperature=0.1, max_tokens=3000)

    flag, raw = _extract_flag(raw)
    if flag:
        cache[f"source_flag|{yaml_path}"] = flag

    if raw.strip() == "CONSISTENT":
        result = {"needs_update": False, "yaml": existing_yaml}
    else:
        corrected = _strip_fences(raw)
        # Safety net: if LLM returned only partial yaml, merge into existing
        corrected = _merge_yaml_update(existing_yaml, corrected)
        # Safety net: never drop human-written options/usage/optionsLocations
        corrected = _preserve_human_content(existing_yaml, corrected)
        # Safety net: preserve toctree directives in description
        try:
            orig_data = yaml.safe_load(existing_yaml) or {}
            new_data = yaml.safe_load(corrected) or {}
            orig_desc = str(orig_data.get("description") or "")
            new_desc = str(new_data.get("description") or "")
            fixed_desc = _preserve_description_toctrees(orig_desc, new_desc)
            if fixed_desc != new_desc:
                new_data["description"] = fixed_desc
                corrected = _yaml_dump(new_data)
        except Exception:
            pass
        # If nothing semantically changed (only re-serialization noise),
        # report the file as consistent so no spurious provenance is added.
        if not _changed_sections(existing_yaml, corrected):
            result = {"needs_update": False, "yaml": existing_yaml}
        else:
            result = {"needs_update": True, "yaml": corrected}

    cache[cache_key] = result
    return result["needs_update"], result["yaml"]


def add_formulation_if_missing(
    client: OpenAI,
    yaml_path: Path,
    source_info: dict,
    existing_yaml: str,
    model: str,
    cache: dict,
) -> tuple[bool, str]:
    """
    Add a `formulation` section to a complete yaml that is missing one,
    if the class appears to implement a physical model (has options or source code).
    Returns (was_added, updated_yaml_or_original).
    """
    # Quick check: skip if formulation already exists or no source found
    if "formulation:" in existing_yaml:
        return False, existing_yaml
    src_ctx = build_source_context(source_info, max_header=6000, max_impl=3000)
    if not src_ctx:
        return False, existing_yaml

    cache_key = f"formulation_v2|{yaml_path}|{model}"
    if cache_key in cache:
        cached = cache[cache_key]
        return cached["added"], cached["yaml"]

    user_prompt = f"""The yaml for `{source_info['class_name']}` is missing a `formulation` section.
Add one if (and only if) this class implements a physical model with non-trivial equations.
If the class is purely a base/abstract class or a thin wrapper with no mathematical model,
respond with exactly: NO_FORMULATION_NEEDED

## Source code:{src_ctx}

## Current yaml:
```yaml
{existing_yaml}
```

Return the full yaml with the new `formulation` field inserted after `description`.
Return only the yaml content (no fences)."""

    raw = _chat(client, model, _SYSTEM_THEORY_WRITER, user_prompt, temperature=0.4, max_tokens=3000)

    if raw.strip() == "NO_FORMULATION_NEEDED":
        result = {"added": False, "yaml": existing_yaml}
    else:
        full = _merge_yaml_update(existing_yaml, _strip_fences(raw))
        result = {"added": True, "yaml": full}

    cache[cache_key] = result
    return result["added"], result["yaml"]


def extend_formulation_if_short(
    client: OpenAI,
    yaml_path: Path,
    source_info: dict,
    existing_yaml: str,
    model: str,
    cache: dict,
) -> tuple[bool, str]:
    """
    Extend a formulation section that exists but is too short to be useful.
    Returns (was_extended, updated_yaml_or_original).
    """
    try:
        data = yaml.safe_load(existing_yaml) or {}
    except Exception:
        return False, existing_yaml

    formulation = data.get("formulation", "")
    if not formulation or len(str(formulation)) >= FORMULATION_EXTEND_MIN_CHARS:
        return False, existing_yaml

    cache_key = f"formulation_extend_v2|{yaml_path}|{model}"
    if cache_key in cache:
        cached = cache[cache_key]
        return cached["extended"], cached["yaml"]

    src_ctx = build_source_context(source_info, max_header=6000, max_impl=3000)

    user_prompt = f"""The `formulation` section for `{source_info['class_name']}` is too brief
to be useful for a graduate student in nuclear engineering:

Current formulation:
{formulation}

Expand it into a thorough, self-contained explanation covering:
- The physical model or mathematical method implemented
- Key equations (use LaTeX math syntax)
- Assumptions and validity range
- References to standard nuclear engineering notation where applicable

## Source code (for context):{src_ctx}

## Full current yaml:
```yaml
{existing_yaml}
```

Return the COMPLETE yaml with the formulation field replaced by the expanded version.
No fences, no extra explanation."""

    raw = _chat(client, model, _SYSTEM_THEORY_WRITER, user_prompt, temperature=0.4, max_tokens=4000)
    full = _merge_yaml_update(existing_yaml, _strip_fences(raw))
    result = {"extended": True, "yaml": full}

    cache[cache_key] = result
    return result["extended"], result["yaml"]


# =============================================================================
# Dry-run report
# =============================================================================

def _unified_diff(old: str, new: str, filename: str) -> str:
    """Return a unified diff string between old and new yaml content."""
    lines = list(difflib.unified_diff(
        old.splitlines(keepends=True),
        new.splitlines(keepends=True),
        fromfile=f"{filename} (original)",
        tofile=f"{filename} (proposed)",
        n=3,
    ))
    return "".join(lines)


def _diff_size(old: str, new: str) -> int:
    """Number of changed lines between old and new."""
    matcher = difflib.SequenceMatcher(None, old.splitlines(), new.splitlines())
    return sum(max(j2 - j1, i2 - i1) for _, i1, i2, j1, j2 in matcher.get_opcodes() if _ != "equal")


def print_dry_run_report(all_results: list[dict], repo_root: Path) -> None:
    """
    Print a human-readable dry-run report:
    - A few newly generated yaml files shown in full
    - Modified files shown as diffs, ranked by change size
      (1 minimal change, 2 heavy changes highlighted)
    """
    SEP = "─" * 72

    generated = [r for r in all_results if r.get("action") == "generated" and "new_content" in r]
    modified  = [r for r in all_results
                 if r.get("action", "") not in ("none", "generated")
                 and "new_content" in r]

    print()
    print("=" * 72)
    print("DRY-RUN REPORT")
    print("=" * 72)
    print(f"  Files that would be generated : {len(generated)}")
    print(f"  Files that would be modified  : {len(modified)}")
    print()

    # ---- Generated files: show up to 3 examples in full --------------------
    if generated:
        print(SEP)
        print("GENERATED (sample — up to 3 files shown in full)")
        print(SEP)
        for r in generated[:3]:
            name = Path(r["path"]).relative_to(repo_root)
            print(f"\n### {name}\n")
            print(r["new_content"])
            print()

        if len(generated) > 3:
            remaining = [str(Path(r["path"]).relative_to(repo_root)) for r in generated[3:]]
            print(f"  ... and {len(remaining)} more:")
            for p in remaining:
                print(f"    {p}")
        print()

    # ---- Modified files: rank by diff size, show 1 minimal + 2 heavy ------
    if modified:
        # Attach diff size and diff text to each result
        enriched = []
        for r in modified:
            original = Path(r["path"]).read_text(encoding="utf-8")
            diff_text = _unified_diff(original, r["new_content"], Path(r["path"]).name)
            size = _diff_size(original, r["new_content"])
            enriched.append((size, diff_text, r))

        enriched.sort(key=lambda x: x[0])  # ascending: smallest change first

        # Pick examples: 1 minimal, 2 heaviest
        to_show: list[tuple] = []
        if len(enriched) >= 1:
            to_show.append(("MINIMAL CHANGE", enriched[0]))
        if len(enriched) >= 2:
            to_show.append(("HEAVY CHANGE (1)", enriched[-1]))
        if len(enriched) >= 3:
            to_show.append(("HEAVY CHANGE (2)", enriched[-2]))

        print(SEP)
        print("MODIFIED FILES (sample — ranked by change size)")
        print(SEP)

        for label, (size, diff_text, r) in to_show:
            name = Path(r["path"]).relative_to(repo_root)
            action = r.get("action", "")
            print(f"\n### [{label}] {name}  (action: {action}, ~{size} lines changed)\n")
            print(diff_text or "  (no textual diff — content reordered)")
            print()

        # List all other modified files without showing diffs
        others = [e for e in enriched if e not in [x[1] for x in to_show]]
        if others:
            print(f"  All {len(modified)} modified files (by change size):")
            for size, _, r in enriched:
                name = Path(r["path"]).relative_to(repo_root)
                print(f"    {size:3d} lines  {name}")
        print()


# =============================================================================
# Per-file orchestration
# =============================================================================

def _resolve_output_path(original: Path, output_dir: Path | None) -> Path:
    """Return the destination path, mirroring repo structure under output_dir."""
    if output_dir is None:
        return original
    rel = original.relative_to(REPO_ROOT)
    dest = output_dir / rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    return dest


def process_yaml_file(
    client: OpenAI,
    yaml_path: Path,
    mode: str,
    model: str,
    theory_model: str,
    add_theory: bool,
    dry_run: bool,
    force: bool,
    few_shot: str,
    cache: dict,
    verbose: bool,
    progress_paths: frozenset = frozenset(),
    output_dir: Path | None = None,
) -> dict:
    """Process a single yaml file according to the requested mode."""
    result: dict = {"path": str(yaml_path), "action": "none", "error": None}

    try:
        existing_yaml = yaml_path.read_text(encoding="utf-8") if yaml_path.exists() else ""
        incomplete = is_incomplete(yaml_path, progress_paths)

        will_generate = mode in ("generate", "all") and (incomplete or force)
        will_check = mode in ("check", "all") and not incomplete

        content_hash = hashlib.md5(existing_yaml.encode()).hexdigest()[:8]
        chk_key = f"check_v4|{yaml_path}|{model}|{content_hash}"
        check_cached = chk_key in cache

        # The generate cache key hashes the source context, so sources must be
        # read up-front when generating; for check-only, skip reads on cache hit.
        needs_source = will_generate or (will_check and not check_cached)
        source_info = find_source_files(yaml_path) if needs_source else {"class_name": yaml_path.stem}

        generate_cached = False
        if will_generate:
            src_ctx = build_source_context(source_info)
            ctx_hash = hashlib.md5((existing_yaml + src_ctx).encode()).hexdigest()[:8]
            gen_key = f"generate_v2|{yaml_path}|{model}|{theory_model}|{add_theory}|{ctx_hash}"
            generate_cached = gen_key in cache

        # Report from_cache accurately: True only when the operation that will
        # actually run is already cached (not just any operation).
        if will_generate:
            result["from_cache"] = generate_cached
        elif will_check:
            result["from_cache"] = check_cached
        else:
            result["from_cache"] = False

        # ---- Generate mode (incomplete files) --------------------------------
        if mode in ("generate", "all") and (incomplete or force):
            # Determine up-front whether this stub already has content worth
            # preserving.  Files with INCOMPLETE_MARKER are auto-generated stubs
            # whose usage should be replaced by tutorial snippets if any exist.
            has_incomplete_marker = INCOMPLETE_MARKER in existing_yaml
            try:
                orig = yaml.safe_load(existing_yaml) or {}
                orig_desc = str(orig.get("description") or "").strip()
                stub_had_content = (
                    len(orig_desc) > 80
                    or bool(orig.get("usage"))
                    or bool(orig.get("options"))
                    or bool(orig.get("externalOptions"))
                )
            except Exception:
                stub_had_content = False

            # Always search for tutorial snippets when the file is marked as
            # auto-generated (INCOMPLETE_MARKER present), even if it already
            # has a usage field — that field may itself be auto-generated.
            tutorial_snippets: list[str] | None = None
            if (not stub_had_content or has_incomplete_marker) and not generate_cached:
                class_name = source_info.get("class_name") or yaml_path.stem
                tutorial_snippets = find_tutorial_usage(class_name, REPO_ROOT)

            new_yaml = generate_yaml(
                client, yaml_path, source_info, existing_yaml,
                few_shot, model, theory_model, add_theory, cache,
                tutorial_snippets=tutorial_snippets,
            )
            # Safety net: restore original usage, non-warning admonitions,
            # and embedded toctree directives if the LLM wiped them.
            # Exception: do NOT restore usage when INCOMPLETE_MARKER was present
            # (the old usage was auto-generated and should be superseded).
            if stub_had_content:
                try:
                    orig_data = yaml.safe_load(existing_yaml) or {}
                    new_data = yaml.safe_load(new_yaml) or {}
                    restored = False
                    if (orig_data.get("usage") and not new_data.get("usage")
                            and not has_incomplete_marker):
                        new_data["usage"] = orig_data["usage"]
                        restored = True
                    orig_adm = [a for a in (orig_data.get("admonitions") or [])
                                if INCOMPLETE_MARKER not in str(a.get("body", ""))]
                    new_adm = [a for a in (new_data.get("admonitions") or [])
                               if INCOMPLETE_MARKER not in str(a.get("body", ""))]
                    if orig_adm and not new_adm:
                        new_data["admonitions"] = orig_adm
                        restored = True
                    # Restore human-written options the LLM dropped from the
                    # stub (a truncated source excerpt is not evidence of
                    # absence — same protection the check path already has).
                    if _restore_dropped_options(orig_data, new_data):
                        restored = True
                    # Preserve toctree directives embedded in the description
                    orig_desc_str = str(orig_data.get("description") or "")
                    new_desc_str = str(new_data.get("description") or "")
                    fixed_desc = _preserve_description_toctrees(orig_desc_str, new_desc_str)
                    if fixed_desc != new_desc_str:
                        new_data["description"] = fixed_desc
                        restored = True
                    if restored:
                        new_yaml = _yaml_dump(new_data)
                except Exception:
                    pass
            if stub_had_content:
                changed = _changed_sections(existing_yaml, new_yaml)
                new_yaml = _set_ai_provenance(new_yaml, model, modified_sections=changed, stub_improved=True)
            else:
                new_yaml = _set_ai_provenance(new_yaml, model, generated=True)
            result["action"] = "generated"
            result["new_content"] = new_yaml
            if not dry_run and new_yaml != existing_yaml:
                _resolve_output_path(yaml_path, output_dir).write_text(new_yaml, encoding="utf-8")

        # ---- Check mode (complete files) --------------------------------------
        elif mode in ("check", "all") and not incomplete:
            needs_update, updated = check_consistency(
                client, yaml_path, source_info, existing_yaml, model, cache
            )
            if needs_update:
                changed = _changed_sections(existing_yaml, updated)
                updated = _set_ai_provenance(updated, model, modified_sections=changed)
                result["action"] = "consistency-updated"
                result["new_content"] = updated
                if not dry_run:
                    _resolve_output_path(yaml_path, output_dir).write_text(updated, encoding="utf-8")
                existing_yaml = updated  # chain into formulation step
                # Pre-populate cache for the new content so a subsequent run
                # recognises the updated file as already-checked and skips it.
                new_hash = hashlib.md5(updated.encode()).hexdigest()[:8]
                cache[f"check_v4|{yaml_path}|{model}|{new_hash}"] = {
                    "needs_update": False, "yaml": updated
                }

            # ---- Add missing formulation sections ----------------------------
            if add_theory and mode in ("check", "all"):
                was_added, with_formulation = add_formulation_if_missing(
                    client, yaml_path, source_info, existing_yaml, theory_model, cache
                )
                if was_added:
                    with_formulation = _set_ai_provenance(
                        with_formulation, theory_model, formulation_added=True
                    )
                    result["action"] = result.get("action", "none") + "+formulation"
                    result["new_content"] = with_formulation
                    existing_yaml = with_formulation
                    if not dry_run:
                        _resolve_output_path(yaml_path, output_dir).write_text(with_formulation, encoding="utf-8")

            # ---- Extend short formulation sections ---------------------------
            if add_theory and mode in ("check", "all"):
                was_extended, with_extended = extend_formulation_if_short(
                    client, yaml_path, source_info, existing_yaml, theory_model, cache
                )
                if was_extended:
                    with_extended = _set_ai_provenance(
                        with_extended, theory_model, formulation_extended=True
                    )
                    result["action"] = result.get("action", "none") + "+formulation-extended"
                    result["new_content"] = with_extended
                    if not dry_run:
                        _resolve_output_path(yaml_path, output_dir).write_text(with_extended, encoding="utf-8")

    except Exception as exc:
        result["error"] = str(exc)
        if verbose:
            print(f"    ERROR: {exc}")

    # Attach any source-content flag raised during generate/check
    flag = cache.get(f"source_flag|{yaml_path}")
    if flag:
        result["source_flag"] = flag

    return result


# =============================================================================
# CLI
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="doc_ai.py",
        description="AI-enhanced documentation generator for foamForNuclear",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Modes:
  generate   Generate yaml files for incomplete/stub classes
  check      Check complete yaml files for consistency with source code,
             add/extend formulation sections, and passively flag inappropriate
             language found in source comments (written to content_flags.md)
  guide      Polish English and formatting of RST/Markdown files in documentation/sphinx/usersguide/
  all        Run generate + check + guide

Examples:
  # Full run with cheap model
  python3 tools/docAI/doc_ai.py --mode all --model gpt-5.4-nano

  # Generate docs for incomplete files using gpt-5.4
  python3 tools/docAI/doc_ai.py --mode generate --model gpt-5.4

  # Polish user guide only
  python3 tools/docAI/doc_ai.py --mode guide --model gpt-5.4

  # Check consistency with a cheap model, theory with a capable one
  python3 tools/docAI/doc_ai.py --mode check --model gpt-5.4-mini --theory-model gpt-5.4

  # Full run, dry-run first
  python3 tools/docAI/doc_ai.py --mode all --dry-run

  # Process specific yaml files only
  python3 tools/docAI/doc_ai.py --files src/offbeatLib/burnup/burnup.yaml

  # Skip theory sections (faster / cheaper)
  python3 tools/docAI/doc_ai.py --mode generate --no-theory
        """,
    )

    parser.add_argument(
        "--mode",
        choices=["generate", "check", "guide", "all"],
        default="generate",
        help="Operation mode (default: generate)",
    )
    parser.add_argument(
        "--model",
        default="gpt-5.4-nano",
        metavar="MODEL",
        help="OpenAI model for code analysis and yaml generation (default: gpt-5.4-nano)",
    )
    parser.add_argument(
        "--theory-model",
        default=None,
        metavar="MODEL",
        help="OpenAI model for formulation/theory writing (default: same as --model)",
    )
    parser.add_argument(
        "--no-theory",
        action="store_true",
        help="Skip adding formulation/theory sections",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would change without writing any files",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-process already complete files in generate mode",
    )
    parser.add_argument(
        "--files",
        nargs="+",
        metavar="FILE",
        help="Process specific yaml files (relative to repo root or absolute)",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        metavar="DIR",
        help=(
            "Write AI-enhanced files to a parallel directory tree instead of "
            "overwriting originals. Paths mirror the repo structure under DIR. "
            "Intended for building the AI documentation variant."
        ),
    )
    parser.add_argument(
        "--no-cache",
        action="store_true",
        help="Disable LLM response caching (useful during development)",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Reduce output verbosity",
    )
    parser.add_argument(
        "--report",
        default=None,
        metavar="FILE",
        help="Save a JSON report of all actions taken (e.g. --report doc_ai_report.json)",
    )
    parser.add_argument(
        "--source-budget",
        type=int,
        default=None,
        metavar="CHARS",
        help="Raise the per-file source-context budget (chars) sent to the model. "
             "Spends more tokens for better option discovery on large files. "
             "Only ever raises a call site's default, never lowers it.",
    )
    parser.add_argument(
        "--full-source",
        action="store_true",
        help="Send whole source files to the model (no truncation). "
             "Maximum token cost; overrides --source-budget.",
    )

    return parser.parse_args()


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    args = parse_args()
    verbose = not args.quiet
    theory_model = args.theory_model or args.model
    add_theory = not args.no_theory
    output_dir = Path(args.output_dir).resolve() if args.output_dir else None

    # A larger source-context budget invalidates the generate/check caches
    # (their keys hash the source excerpt), so changed files are re-processed.
    global SOURCE_BUDGET_OVERRIDE
    if args.full_source:
        SOURCE_BUDGET_OVERRIDE = 10_000_000
    elif args.source_budget is not None:
        SOURCE_BUDGET_OVERRIDE = args.source_budget

    if verbose:
        print("foamForNuclear AI Documentation Generator")
        print(f"  Repo root       : {REPO_ROOT}")
        print(f"  Mode            : {args.mode}")
        print(f"  Model           : {args.model}")
        print(f"  Theory model    : {theory_model}")
        print(f"  Add theory      : {add_theory}")
        print(f"  Dry run         : {args.dry_run}")
        print(f"  Output dir      : {output_dir or '(in-place)'}")
        if SOURCE_BUDGET_OVERRIDE is not None:
            budget_label = "whole files" if args.full_source else f"{SOURCE_BUDGET_OVERRIDE} chars"
            print(f"  Source budget   : {budget_label}")
        print()

    client = get_client()

    # --- Cache ----------------------------------------------------------------
    cache_path = _SCRIPT_DIR / ".llm_cache.json"
    cache: dict = {}
    if not args.no_cache and cache_path.exists():
        with open(cache_path, encoding="utf-8") as fh:
            cache = json.load(fh)
        if verbose:
            print(f"Loaded {len(cache)} cached LLM responses from {cache_path.name}")

    def save_cache() -> None:
        if not args.no_cache:
            with open(cache_path, "w", encoding="utf-8") as fh:
                json.dump(cache, fh, indent=2)

    # --- Build shared context -------------------------------------------------
    few_shot = load_few_shot_examples(REPO_ROOT)
    sphinx_index = load_sphinx_index(REPO_ROOT)
    if verbose and sphinx_index:
        print(f"Loaded sphinx index ({len(sphinx_index)} chars) as project context.")
        print()

    progress_paths = load_progress_paths(REPO_ROOT)

    all_results: list[dict] = []

    # =========================================================================
    # Documentation generation / consistency checking
    # =========================================================================
    if args.mode in ("generate", "check", "all"):

        # Determine which files to process
        if args.files:
            yaml_files: list[Path] = []
            for f in args.files:
                p = Path(f)
                if not p.is_absolute():
                    p = REPO_ROOT / p
                yaml_files.append(p)  # include even if missing; is_incomplete handles it
        else:
            yaml_files = find_all_yaml_files(REPO_ROOT)

        # Filter by mode
        if args.mode == "generate" and not args.force:
            to_process = [f for f in yaml_files if is_incomplete(f, progress_paths)]
        elif args.mode == "check":
            to_process = [f for f in yaml_files if not is_incomplete(f, progress_paths)]
        else:  # all
            to_process = yaml_files

        if verbose:
            mode_label = args.mode if args.mode != "all" else "generate+check"
            print(f"=== Documentation ({mode_label}) ===")
            print(f"Total yaml files   : {len(yaml_files)}")
            incomplete_count = sum(1 for f in yaml_files if is_incomplete(f, progress_paths))
            print(f"Incomplete (stub)  : {incomplete_count}")
            print(f"Files to process   : {len(to_process)}")
            if args.dry_run:
                print("  [DRY RUN — no files will be written]")
            print()

        generated = updated = formulation_added = formulation_extended = errors = 0

        for i, yaml_path in enumerate(to_process, 1):
            rel = yaml_path.relative_to(REPO_ROOT)
            if verbose:
                # Cache status is checked inside process_yaml_file; print after
                pass

            file_result = process_yaml_file(
                client=client,
                yaml_path=yaml_path,
                mode=args.mode,
                model=args.model,
                theory_model=theory_model,
                add_theory=add_theory,
                dry_run=args.dry_run,
                force=args.force,
                few_shot=few_shot,
                cache=cache,
                verbose=verbose,
                progress_paths=progress_paths,
                output_dir=output_dir,
            )
            all_results.append(file_result)

            action = file_result.get("action", "none")
            cached_tag = " [cached]" if file_result.get("from_cache") else ""
            if verbose:
                print(f"[{i}/{len(to_process)}] {rel}{cached_tag}")

            if "generated" in action:
                generated += 1
                if verbose:
                    print(f"    -> generated")
            if "consistency-updated" in action:
                updated += 1
                if verbose:
                    print(f"    -> consistency fixed")
            if "+formulation-extended" in action:
                formulation_extended += 1
                if verbose:
                    print(f"    -> formulation extended")
            elif "+formulation" in action:
                formulation_added += 1
                if verbose:
                    print(f"    -> formulation added")
            if file_result.get("error"):
                errors += 1

            # Save cache periodically
            if i % 10 == 0:
                save_cache()

            # Skip rate-limit delay when result came from cache
            if not file_result.get("from_cache"):
                time.sleep(API_RATE_DELAY)

        # Collect source-content flags raised during generate/check
        source_flags = [
            (r["path"], r["source_flag"])
            for r in all_results
            if r.get("source_flag")
        ]

        print()
        print("Summary:")
        print(f"  Generated           : {generated}")
        print(f"  Consistency fixed   : {updated}")
        print(f"  Formulation added   : {formulation_added}")
        print(f"  Formulation extended: {formulation_extended}")
        print(f"  Source flags        : {len(source_flags)}")
        print(f"  Errors              : {errors}")

        if source_flags:
            print("\nFlagged source files (see tools/docAI/content_flags.md):")
            for path, reason in source_flags:
                rel = Path(path).relative_to(REPO_ROOT)
                print(f"  {rel}  —  {reason}")

        # Write / update content_flags.md
        flags_path = REPO_ROOT / "tools" / "docAI" / "content_flags.md"
        if source_flags:
            lines = ["# Source content flags\n",
                     "Files flagged by the AI doc generator for potentially inappropriate"
                     " language in source comments.\n",
                     "Fix the issue, then remove the entry.\n\n"]
            for path, reason in source_flags:
                rel = Path(path).relative_to(REPO_ROOT)
                # Link to the adjacent source file, not the yaml
                src_candidates = list(Path(path).parent.glob(
                    Path(path).stem + ".H"
                )) + list(Path(path).parent.glob(Path(path).stem + ".C"))
                src_link = str(Path(src_candidates[0]).relative_to(REPO_ROOT)) \
                    if src_candidates else str(rel)
                lines.append(f"- [{src_link}]({src_link})  —  {reason}\n")
            flags_path.write_text("".join(lines), encoding="utf-8")
        elif flags_path.exists():
            # All flags resolved — clear the file
            flags_path.write_text(
                "# Source content flags\n\nNo issues found.\n", encoding="utf-8"
            )

        if args.dry_run:
            doc_results = [r for r in all_results if "path" in r]
            print_dry_run_report(doc_results, REPO_ROOT)

    # =========================================================================
    # User guide polishing
    # =========================================================================
    if args.mode in ("guide", "all"):
        rst_files = find_all_guide_files(REPO_ROOT)

        if verbose:
            print(f"=== User guide polishing ===")
            print(f"Guide files to process (rst+md): {len(rst_files)}")
            if args.dry_run:
                print("  [DRY RUN — no files will be written]")
            print()

        guide_polished = guide_skipped = guide_errors = 0

        for i, rst_path in enumerate(rst_files, 1):
            rel = rst_path.relative_to(REPO_ROOT)
            result = polish_guide_file(
                client=client,
                rst_path=rst_path,
                model=args.model,
                cache=cache,
                dry_run=args.dry_run,
                verbose=verbose,
                output_dir=output_dir,
            )
            all_results.append(result)

            cached_tag = " [cached]" if result.get("from_cache") else ""
            if verbose:
                print(f"[{i}/{len(rst_files)}] {rel}{cached_tag}")

            if result.get("error"):
                guide_errors += 1
                if verbose:
                    print(f"    ERROR: {result['error']}")
            elif result.get("action") == "polished":
                guide_polished += 1
                if verbose:
                    print(f"    -> polished")
            else:
                guide_skipped += 1

            if not result.get("from_cache"):
                time.sleep(API_RATE_DELAY)

            if i % 10 == 0:
                save_cache()

        # --- Introductions for skeleton index pages (title + toctree only) ----
        skeleton_indexes = find_skeleton_index_files(REPO_ROOT)
        intros_added = 0
        if verbose and skeleton_indexes:
            print()
            print(f"Skeleton index pages needing an intro: {len(skeleton_indexes)}")
        for j, idx_path in enumerate(skeleton_indexes, 1):
            rel = idx_path.relative_to(REPO_ROOT)
            res = generate_index_intro(
                client=client,
                rst_path=idx_path,
                model=args.model,
                cache=cache,
                dry_run=args.dry_run,
                output_dir=output_dir,
            )
            all_results.append(res)
            cached_tag = " [cached]" if res.get("from_cache") else ""
            if verbose:
                print(f"[intro {j}/{len(skeleton_indexes)}] {rel}{cached_tag}")
            if res.get("action") == "intro-added":
                intros_added += 1
                if verbose:
                    print("    -> intro added")
            if not res.get("from_cache"):
                time.sleep(API_RATE_DELAY)
            if j % 10 == 0:
                save_cache()

        print()
        print("User guide summary:")
        print(f"  Polished     : {guide_polished}")
        print(f"  Unchanged    : {guide_skipped}")
        print(f"  Intros added : {intros_added}")
        print(f"  Skipped (validation failed): {guide_errors}")

    # --- Final cache save + report -------------------------------------------
    save_cache()

    if args.report:
        with open(args.report, "w", encoding="utf-8") as fh:
            json.dump(all_results, fh, indent=2)
        print(f"\nReport saved to: {args.report}")


if __name__ == "__main__":
    main()
