#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cases="legacySolver newSolver"

for caseName in $cases
do
    printf "Preparing to run case $caseName...\n"

    # Start gnuplot if it exist
    if command -v gnuplot &> /dev/null
    then
        gnuplot -e "log='$caseName/log.GeN-Foam'" residuals - &> /dev/null &
    else
        echo "gnuplot could not be found"
    fi

    printf "Running GeN-Foam on $caseName\n"
    decomposePar -case $caseName -allRegions
    mpirun -np 4 GeN-Foam -parallel -case $caseName | tee "$caseName/log.GeN-Foam"

    # Kill gnuplot if it was started
    pkill -x gnuplot &> /dev/null

done

#------------------------------------------------------------------------------
