#!/bin/sh
exe="GeN-Foam"

# Start gnuplot if it exist
if command -v gnuplot &> /dev/null
then
    gnuplot -e "log='log.GeN-Foam'" residuals - &> /dev/null &
else
    echo "gnuplot could not be found"
fi

# Run GeN-Foam
GeN-Foam | tee "log.GeN-Foam"

# Kill gnuplot if it was started
pkill -x gnuplot &> /dev/null &
