#!/bin/sh
exe="GeN-Foam"

# Start gnuplot if it exist
if ! command -v gnuplot &> /dev/null
then
    echo "gnuplot could not be found"
else
    gnuplot residuals - &> /dev/null &
fi

# Run GeN-Foam
$exe | tee log.GeN-Foam

# Kill gnuplot if it was started
if command -v gnuplot &> /dev/null
then
    pkill -x gnuplot
fi
