#!/bin/sh
# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh
runApplication -o changeDictionary
runApplication -o offbeat

runApplication -o postProcess -func sampleDict

stressSimulationIPyC=$(cat postProcessing/probes/0/sigma |tail -n 1| cut -d"(" -f2 | cut -d")" -f1 | cut -d" " -f6)
stressSimulationSiC=$(cat postProcessing/probes/0/sigma |tail -n 1| cut -d"(" -f3 | cut -d")" -f1 | cut -d" " -f6)

#
stressExpectedIPyC=2.91593e+07
stressExpectedSiC=7.86904e+07
#
echo "Tangential stress at inner surface of IPyC: $stressSimulationIPyC" >> results
echo "Previous value: $stressExpectedIPyC" >> results
echo "Range of other codes: [25e6, 35e6]" >> results
echo "Tangential stress at inner surface of SiC: $stressSimulationSiC" >> results
echo "Previous value: $stressExpectedSiC" >> results
echo "Range of other codes: [71e6, 88e6]" >> results
#
relErrorIPyC=$(awk -v var1="$stressSimulationIPyC" \
                    -v var2="$stressExpectedIPyC" \
                'BEGIN {print (100*(var1-var2)/var2)}')

relErrorSiC=$(awk -v var1="$stressSimulationSiC" \
                -v var2="$stressExpectedSiC" \
                'BEGIN {print (100*(var1-var2)/var2)}')

echo "Relative change for IPyC: $relErrorIPyC%" >> results
echo "Relative change for SiC: $relErrorSiC%" >> results
