#!/bin/sh
# Tutorial prepared based on the PhD work of Peter German (Texas A&M, peter.german@tamu.edu)

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

exe="GeN-Foam"

cases="steadyState transient transientEnd"

runCloneCase()
{
    printf "Cloning $2 to case $1..."
    cp -r $2 $1
    printf "$2 cloned!\n"
}

setSteadyState()
{
    caseName=$1
    runCloneCase $caseName $2
    printf "Setting steady state case...\n"
    foamDictionary $caseName/system/controlDict -entry startFrom -set startTime
    foamDictionary $caseName/system/controlDict -entry startTime -set 0
    foamDictionary $caseName/system/controlDict -entry endTime -set 100
    foamDictionary $caseName/system/controlDict -entry adjustTimeStep -set true
    foamDictionary $caseName/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $caseName/system/controlDict -entry writeInterval -set 100
    cp $caseName/constant/multiRegionCouplingDict_TH $caseName/constant/multiRegionCouplingDict
    GeN-Foam -initializeMappedFields -case $caseName
    printf "Case set!\n\n"
}


setTransient()
{
    caseName=$1
    runCloneCase $caseName $2
    cp -r $caseName/0/neutroRegion $caseName/100/ 
    cp -r $caseName/0/uniform $caseName/100/ 
    printf "Setting $caseName case...\n"
    foamDictionary $caseName/system/controlDict -entry startFrom -set startTime
    foamDictionary $caseName/system/controlDict -entry startTime -set 100
    foamDictionary $caseName/system/controlDict -entry endTime -set 400
    foamDictionary $caseName/system/controlDict -entry adjustTimeStep -set true
    foamDictionary $caseName/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $caseName/system/controlDict -entry writeInterval -set 10
    foamDictionary $caseName/system/controlDict -entry  regionSolvers/neutroRegion -set pointKinetics
    foamDictionary $caseName/system/controlDict -entry  removeBaffles/neutroRegion -set false
    # rm $caseName/constant/multiRegionCouplingDict
    cp $caseName/constant/multiRegionCouplingDict_Coupled $caseName/constant/multiRegionCouplingDict
    GeN-Foam -initializeMappedFields -case $caseName
    printf "Case set!\n\n"
}

setTransientEnd()
{
    caseName=$1
    runCloneCase $caseName $2
    printf "Setting $caseName case...\n"
    foamDictionary $caseName/system/controlDict -entry startFrom -set startTime
    foamDictionary $caseName/system/controlDict -entry startTime -set 400
    foamDictionary $caseName/system/controlDict -entry endTime -set 401
    foamDictionary $caseName/system/controlDict -entry adjustTimeStep -set true
    foamDictionary $caseName/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $caseName/system/controlDict -entry writeInterval -set 1
    GeN-Foam -initializeMappedFields -case $caseName

    printf "Case set!\n\n"
}

for caseName in $cases
do
    printf "Preparing to run case $caseName...\n"

    case "$caseName" in
        "steadyState")
            setSteadyState $caseName rootCase
            printf "Steady state th case is prepared!\n"
            ;;
        "transient")
            printf "Transient case entered...\n"
            setTransient $caseName steadyState
            ;;
        "transientEnd")
            printf "Transient case entered...\n"
            setTransientEnd $caseName transient
            ;;
    esac

    # Start gnuplot if it exist
    if command -v gnuplot &> /dev/null
    then
        gnuplot -e "log='$caseName/log.$exe'" residuals - &> /dev/null &
    else
        echo "gnuplot could not be found"
    fi

    #( cd $caseName && runApplication `getApplication` )
    printf "Running $exe on $caseName\n"
    #set point kinetics initial conditions
    $exe -case $caseName 2>&1 | tee "$caseName/log.$exe"

    # Kill gnuplot if it was started
    pkill -x gnuplot &> /dev/null

done

#------------------------------------------------------------------------------
