#!/bin/sh
# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh
runApplication -o changeDictionary
runApplication -o offbeat
#
runApplication -o postProcess -func sampleDict

centerTempSimulation=$(cat postProcessing/probes/0/T |tail -n 1| awk '{print $NF}')

centerTempExpected=459.66666667
#
echo "center temperature: $centerTempSimulation" >> results
echo "Expected value: $centerTempExpected" >> results

relErrorCenterTemp=`echo - | awk '{print 100*(var1-var2)/var2}' \
var1="$centerTempSimulation" var2="$centerTempExpected"`

echo "Relative error for center temperature: $relErrorCenterTemp%" >> results
