#!/bin/bash

# --- Run from this directory
cd ${0%/*} || exit 1

# --- Initialize the output file
resFile=test.out
rm -rf $resFile
touch $resFile

# --- Run the simulation
echo -e "Run tutorial 1D_MSR_pointKinetics ...\n" | tee -a $resFile
./Allrun >> log.simulation
echo -e "Done running tutorial 1D_MSR_pointKinetics ...\n" | tee -a $resFile

# --- Check it ran
isConverge()
{
    folder=$1
    name=$2
    string=$(tail -3 ./$folder/log.GeN-Foam | grep End)
    if [ "$string" = "End" ]; then
        echo -e "$name has converged \n" | tee -a $resFile
    else
        echo -e "$name has NOT converged \n" | tee -a $resFile
        exit 1
    fi
}
isConverge steadyState "Steady state"
isConverge transient "Transient"
isConverge transientEnd "Transient end"

# --- Recover the results
power=$(grep totalPower ./transient/log.GeN-Foam | tail -1 | awk '{ printf "%.0f\n", $3 }')
expectedAt=613794000

# --- Check results are correct
isInRange()
{
    ref=$1
    value=$2
    error=$3
    valueMin=$(bc -l <<<"$value*(1-$error)")
    valueMax=$(bc -l <<<"$value*(1+$error)")
    if (( $(echo "$valueMin <= $ref && $ref <= $valueMax" | bc -l) )); then
        echo 0
    elif (( $(echo "$valueMax <= $ref && $ref <= $valueMin" | bc -l) )); then
        echo 0
    else
        echo 1
    fi
}

# --- Check that results are correct
error=0.01
echo "Power at the end of transient with $error relative error" | tee -a $resFile
if [ $(isInRange $expectedAt $power $error) -eq 0 ]; then
    echo "Perfect match:" | tee -a $resFile
    echo "|       | Simulated | Expected |" | tee -a $resFile
    echo "|:------|:---------:|:--------:|" | tee -a $resFile
    echo "| Power | $power | $expectedAt |" | tee -a $resFile
else
    echo "Divergent results:" | tee -a $resFile
    echo "|       | Simulated | Expected |" | tee -a $resFile
    echo "|:------|:---------:|:--------:|" | tee -a $resFile
    echo "| Power | $power | $expectedAt |" | tee -a $resFile
    exit 1
fi

# --- Exit successfully
exit 0
