#!/bin/sh
#----------------------------------------------------------------------------#
#       ______          _   __           ______                              #
#      / ____/  ___    / | / /          / ____/  ____   ____ _   ____ ___    #
#     / / __   / _ \  /  |/ /  ______  / /_     / __ \ / __ `/  / __ `__ \   #
#    / /_/ /  /  __/ / /|  /  /_____/ / __/    / /_/ // /_/ /  / / / / / /   #
#    \____/   \___/ /_/ |_/          /_/       \____/ \__,_/  /_/ /_/ /_/    #
#    Copyright (C) 2015 - 2022 EPFL                                          #
#----------------------------------------------------------------------------#

cd ${0%/*} || exit 1    # Run from this directory

#==============================================================================*

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#==============================================================================*

cases="steadyState transientNoDriveline transientWithDriveline transientWithBoron"

runCloneCase()
{
    printf "Cloning $1 to case $2..."
    cp -r $1 $2
    printf "$1 cloned!\n"
}

setSteadyState()
{
    runCloneCase $1 $2
    printf "Setting steady state...\n"
    foamDictionary $2/system/controlDict -entry startTime -set 0
    foamDictionary $2/system/controlDict -entry endTime -set 100
    foamDictionary $2/system/controlDict -entry deltaT -set 1
    foamDictionary $2/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $2/system/controlDict -entry writeInterval -set 100
    cp dictionaries/steadyState/neutronicsProperties $2/constant/neutroRegion/neutronicsProperties
    cp dictionaries/steadyState/regionsDict $2/system/regionsDict
    foamDictionary $2/constant/neutroRegion/neutronicsProperties -entry eigenvalueNeutronics -set true
    GeN-Foam -initializeMappedFields -case $2
}

setTransientNoDriveline()
{
    runCloneCase $1 $2
    printf "Setting transient without driveline case...\n"
    foamDictionary $2/system/controlDict -entry startTime -set 100
    foamDictionary $2/system/controlDict -entry endTime -set 200
    foamDictionary $2/system/controlDict -entry deltaT -set 1e-6
    foamDictionary $2/system/controlDict -entry writeControl -set timeStep
    foamDictionary $2/system/controlDict -entry writeInterval -set 10
    cp dictionaries/transient/neutronicsProperties_noBoron $2/constant/neutroRegion/neutronicsProperties
    foamDictionary $2/constant/neutroRegion/neutronicsProperties -entry nuclearData.absoluteDrivelineExpansionCoeff -set 0.0
    foamDictionary $2/constant/neutroRegion/neutronicsProperties -entry eigenvalueNeutronics -set false
    cp dictionaries/transient/regionsDict $2/system/regionsDict
    GeN-Foam -initializeMappedFields -case $2
}

setTransientWithDriveline()
{
    runCloneCase $1 $2
    printf "Setting transient with driveline case...\n"
    foamDictionary $2/system/controlDict -entry startTime -set 100
    foamDictionary $2/system/controlDict -entry endTime -set 200
    foamDictionary $2/system/controlDict -entry deltaT -set 1e-6
    foamDictionary $2/system/controlDict -entry writeControl -set timeStep
    foamDictionary $2/system/controlDict -entry writeInterval -set 10
    cp dictionaries/transient/neutronicsProperties_noBoron $2/constant/neutroRegion/neutronicsProperties
    foamDictionary $2/constant/neutroRegion/neutronicsProperties -entry nuclearData.absoluteDrivelineExpansionCoeff -set 8e-5
    foamDictionary $2/constant/neutroRegion/neutronicsProperties -entry eigenvalueNeutronics -set false
    cp dictionaries/transient/regionsDict $2/system/regionsDict
    GeN-Foam -initializeMappedFields -case $2
}


setTransientWithBoron()
{
    runCloneCase $1 $2
    printf "Setting transient with driveline case...\n"
    cp dictionaries/transient/neutronicsProperties_withBoron $2/constant/neutroRegion/neutronicsProperties
    foamDictionary $2/constant/neutroRegion/neutronicsProperties -entry eigenvalueNeutronics -set false
    foamDictionary $2/constant/neutroRegion/neutronicsProperties -entry nuclearData.absoluteDrivelineExpansionCoeff -set 0.0
    foamDictionary $2/system/controlDict -entry startTime -set 100
    foamDictionary $2/system/controlDict -entry endTime -set 200
    foamDictionary $2/system/controlDict -entry deltaT -set 1e-6
    foamDictionary $2/system/controlDict -entry writeControl -set timeStep
    foamDictionary $2/system/controlDict -entry writeInterval -set 10
    cp dictionaries/transient/regionsDict $2/system/regionsDict
    GeN-Foam -initializeMappedFields -case $2
}

for caseName in $cases
do
    case "$caseName" in
        "steadyState")
            setSteadyState rootCase $caseName
            ;;
        "transientNoDriveline")
            setTransientNoDriveline steadyState $caseName
            ;;
        "transientWithDriveline")
            setTransientWithDriveline steadyState $caseName
            ;;
        "transientWithBoron")
            setTransientWithBoron steadyState $caseName
            ;;
    esac

    # Start gnuplot if it exist
    if command -v gnuplot &> /dev/null
    then
        gnuplot -e "log='$caseName/log.GeN-Foam'" residuals - &> /dev/null &
    else
        echo "gnuplot could not be found"
    fi

    printf "Running GeN-Foam on $caseName\n"
    GeN-Foam -case $caseName 2>&1 | tee "$caseName/log.GeN-Foam"

    # Kill gnuplot if it was started
    pkill -x gnuplot &> /dev/null &

done


#==============================================================================*
