#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

exe="GeN-Foam"

endTimeSS=900
endTimeT=1505

cases="steadyState transient"

runCloneCase()
{
    printf "Cloning $2 to case $1\n"
    cp -r $2 $1
    printf "$2 cloned!\n"
}

setSteadyState()
{
    runCloneCase $1 $2

    printf "Setting steady state case\n"

    foamDictionary $1/system/controlDict -entry startFrom -set startTime
    foamDictionary $1/system/controlDict -entry startTime -set 0
    foamDictionary $1/system/controlDict -entry endTime -set $endTimeSS
    foamDictionary $1/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $1/system/controlDict -entry writeInterval -set $endTimeSS
    foamDictionary $1/system/controlDict -entry solveFluidMechanics -set true
    foamDictionary $1/system/controlDict -entry solveEnergy -set true
    foamDictionary $1/system/controlDict -entry solveNeutronics -set false
    foamDictionary $1/system/controlDict -entry maxCo -set 500;
    printf "Case set!\n\n"
}

setTransient()
{
    runCloneCase $1 $2

    printf "Setting transient case\n"
    
    foamDictionary $1/system/controlDict -entry startFrom -set startTime
    foamDictionary $1/system/controlDict -entry startTime -set $endTimeSS
    foamDictionary $1/system/controlDict -entry endTime -set $endTimeT
    foamDictionary $1/system/controlDict -entry writeControl -set timeStep
    foamDictionary $1/system/controlDict -entry writeInterval -set 50
    foamDictionary $1/system/controlDict -entry solveFluidMechanics -set true
    foamDictionary $1/system/controlDict -entry solveEnergy -set true
    foamDictionary $1/system/controlDict -entry solveNeutronics -set true
    foamDictionary $1/system/controlDict -entry maxCo -set 10;
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.h -set 0.95
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.hFinal -set 1.0
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.U -set 1.0
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.UFinal -set 1.0
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.p_rgh -set 1.0
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.p_rghFinal -set 1.0
    printf "Case set!\n\n"
}

for caseName in $cases
do
    printf "Preparing to run case $caseName\n"

    case "$caseName" in
    "steadyState")
        setSteadyState $caseName rootCase
        decomposePar -case $caseName -region fluidRegion
        decomposePar -case $caseName -region thermoMechanicalRegion
        decomposePar -case $caseName -region neutroRegion
        ;;
    "transient")
        setTransient $caseName steadyState
        ;;
    esac

    printf "Running $exe on $caseName\n"
    
    mpirun -np 5 $exe -parallel -case $caseName | tee "$caseName/log"

    case "$caseName" in
        "transient")
        reconstructPar -case $caseName -region fluidRegion
        reconstructPar -case $caseName -region thermoMechanicalRegion
        reconstructPar -case $caseName -region neutroRegion
        ;;
    esac

done
