#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

exe="GeN-Foam"

endTimeN=1
endTimeSS=900
endTimeT=1200

# cases="transient"
cases="steadyStateN steadyState transient"

runCloneCase()
{
    printf "Cloning $2 to case $1\n"
    cp -r $2 $1
    printf "$2 cloned!\n"
}

setSteadyStateN()
{
    runCloneCase $1 $2

    printf "Setting steady state neutronics case\n"

    foamDictionary $1/system/controlDict -entry endTime -set $endTimeN
    foamDictionary $1/system/controlDict -entry writeInterval -set $endTimeN
    foamDictionary $1/system/controlDict -entry maxDeltaT -set 2.0
    foamDictionary $1/system/controlDict -entry regionSolvers.neutroRegion -set diffusionNeutronics
    foamDictionary $1/system/controlDict -entry removeBaffles.neutroRegion -set false
    foamDictionary $1/constant/neutroRegion/neutronicsProperties -entry eigenvalueNeutronics -set true
    cp $1/constant/multiRegionCouplingDict_steadyStateN $1/constant/multiRegionCouplingDict
    GeN-Foam -initializeMappedFields -case $1
    printf "Case set!\n\n"
}

setSteadyState()
{
    runCloneCase $1 $2

    printf "Setting steady state case\n"

    for i in {0..4}
    do
        cp -r $1/processor$i/0/fluidRegion $1/processor$i/$endTimeN/
    done

    foamDictionary $1/system/controlDict -entry endTime -set $endTimeSS
    # foamDictionary $1/system/controlDict -entry writeControl -set adjustableRunTime
    foamDictionary $1/system/controlDict -entry writeInterval -set $(($endTimeSS - $endTimeN))
    # foamDictionary $1/system/controlDict -entry solveFluidMechanics -set true
    # foamDictionary $1/system/controlDict -entry solveEnergy -set true
    # foamDictionary $1/system/controlDict -entry solveNeutronics -set false
    foamDictionary $1/system/controlDict -entry maxCo -set 50.0
    foamDictionary $1/system/controlDict -entry maxDeltaT -set 2.0
    foamDictionary $1/system/controlDict -entry regionSolvers.neutroRegion -remove
    # foamDictionary $1/system/controlDict -entry regionSolvers.fluidRegion -set onePhase
    foamDictionary $1/system/controlDict -entry removeBaffles.fluidRegion -set true
    foamDictionary $1/system/controlDict -entry regionSolvers.energyNeutroMechLoop -set multiPhysicsSolver
    # cp $1/constant/multiRegionCouplingDict_steadyState $1/constant/multiRegionCouplingDict
    cp $1/constant/multiRegionCouplingDict_steadyStateTH $1/constant/multiRegionCouplingDict
    GeN-Foam -initializeMappedFields -case $1
    printf "Case set!\n\n"
}

setTransient()
{
    runCloneCase $1 $2

    printf "Setting transient case\n"

    for i in {0..4}
    do
        cp -r $1/processor$i/$endTimeN/neutroRegion $1/processor$i/$endTimeSS/
        cp -r $1/processor$i/$endTimeN/uniform/reactorState $1/processor$i/$endTimeSS/uniform
    done

    foamDictionary $1/system/controlDict -entry endTime -set $endTimeT
    foamDictionary $1/system/controlDict -entry writeControl -set timeStep
    foamDictionary $1/system/controlDict -entry writeInterval -set 50
    # foamDictionary $1/system/controlDict -entry solveFluidMechanics -set true
    # foamDictionary $1/system/controlDict -entry solveEnergy -set true
    # foamDictionary $1/system/controlDict -entry solveNeutronics -set true
    foamDictionary $1/system/controlDict -entry maxCo -set 1.0;
    # foamDictionary $1/system/controlDict -entry regionSolvers.neutroRegion -set pointKinetics
    foamDictionary $1/system/controlDict -entry removeBaffles.neutroRegion -set false
    foamDictionary $1/constant/neutroRegion/neutronicsProperties -entry eigenvalueNeutronics -set false
    # foamDictionary $1/system/fvSolution -entry tightlyCoupled -set true;
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.h -set 0.8
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.hFinal -set 1.0
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.U -set 0.8
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.UFinal -set 1.0
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.p_rgh -set 0.8
    foamDictionary $1/system/fluidRegion/fvSolution -entry relaxationFactors.equations.p_rghFinal -set 1.0
    foamDictionary $1/system/controlDict -entry maxDeltaT -set 1;
    foamDictionary $1/system/controlDict -entry regionSolvers.neutroRegion -remove
    foamDictionary $1/system/controlDict -entry regionSolvers.fluidRegion -remove
    foamDictionary $1/system/controlDict -entry regionSolvers.energyNeutroMechLoop -set multiPhysicsSolver
    cp $1/constant/multiRegionCouplingDict_transient $1/constant/multiRegionCouplingDict
    GeN-Foam -initializeMappedFields -case $1
    printf "Case set!\n\n"
}

for caseName in $cases
do
    if [ ! -d $caseName ]
    then
        printf "Preparing to run case $caseName\n"

        case "$caseName" in
            "steadyStateN")
                setSteadyStateN $caseName rootCase
                decomposePar -case $caseName -allRegions
                ;;
            "steadyState")
                setSteadyState $caseName steadyStateN
                ;;
            "transient")
                setTransient $caseName steadyState
                ;;
        esac

        # Start gnuplot if it exist
        if command -v gnuplot &> /dev/null
        then
            gnuplot -e "log='$caseName/log.$exe'" residuals - &> /dev/null &
        else
            echo "gnuplot could not be found"
        fi

        touch $caseName/foam.foam

        printf "Running $exe on $caseName\n"
        mpirun -np 5 $exe -parallel -case $caseName | tee "$caseName/log.$exe"

        # Kill gnuplot if it was started
        pkill -x gnuplot &> /dev/null

        # reconstructPar -case $caseName -allRegions -latestTime

        # case "$caseName" in
        #     "transient")
        #     reconstructPar -case $caseName -allRegions
        #     ;;
        # esac
    else
        echo "$caseName case already exist"
    fi
done
