"""
To be exectute at the root of this repo
"""

#==============================================================================*
# Imports

import os
import sys

#===============================================================================*
# User input

verbose: int = 1

folders_to_exclude = ['thirdParty', 'documentation']

files_to_exclude = ['.gitlab-ci.yml']


#===============================================================================*

script_name: str = sys.argv[0]

files_to_exclude.append(script_name)

folder = os.getcwd()

warning_flag = """
- kind: warning
    body: |-
      Preliminary autogenerated documentation. Please refer to the source code and tutorials for more reliable information.
""".strip()


#==============================================================================*

n_total_yaml = 0

files_not_completed = []

for root, dirs, files in os.walk(folder):
    for filename in files:
        filepath = os.path.join(root, filename)

        # Exclude current script and thirdParty package
        if (
            filename in files_to_exclude
            or any([folder_to_exclude in filepath for folder_to_exclude in folders_to_exclude])
        ):
            continue

        if (filename[-5:] != '.yaml'):
            continue

        try:
            with open(filepath, "r") as file:
                file_contents = file.read()

            n_total_yaml += 1

            if (warning_flag in file_contents):
                files_not_completed.append(filepath.split("foamForNuclear/")[-1])
                print(f"File {filepath} not completed")


        except UnicodeDecodeError:
            if (verbose >= 2):
                print(f'Skipped file {filepath} due to UnicodeDecodeError')

        except:
            print(f"Impossible to open {filepath}")


#==============================================================================*
# Write report

n_incomplete_yaml = len(files_not_completed)

n_complete_yaml = n_total_yaml - n_incomplete_yaml

progress_fraction = n_complete_yaml/n_total_yaml*100

print(f"Number of `.yaml` files completed: {n_complete_yaml}/{n_total_yaml} ({progress_fraction:.1f} %)")

progress_text = f"""
# YAML Documentation Progress

## Status

Number of `.yaml` files completed: **{n_complete_yaml}/{n_total_yaml} ({progress_fraction:.1f} %)**


## How to complete a file

Remove the following block from the `.yaml`

```yaml
  {warning_flag}
```


## How to regenerate this file

Execute the following code at the root of the foamForNuclear repository

```bash
python3 {script_name}
```


## Files to be completed

**Links are clickable and directs you directly to the file.**

"""

# Create 2 versions, one for the repo display and one for the online
# documentation
progress_text_repo = progress_text
progress_text_doc = progress_text

current_section = None

for i, filepath in enumerate(files_not_completed):
    # file_section = filepath.split('/')[-3]

    # if (file_section != current_section):
    #     progress_text += f"\n\n### {file_section}\n\n"
    #     current_section = file_section

    progress_text_repo += f"{i+1}. [{filepath}](../{filepath}) \n"

    progress_text_doc += f"{i+1}. [{filepath}](https://gitlab.com/foamForNuclear/foamForNuclear/-/blob/docs/{filepath}) \n"


# with open("documentation/yaml_progress.md", 'w') as f:
#     f.write(progress_text_repo)

with open("documentation/sphinx/cppapi/yaml_progress.md", 'w') as f:
    f.write(progress_text_doc)


#==============================================================================*
