#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

if [ -d 0.converged ]
then
    rm -r 0
    cp -r 0.converged 0
fi

runApplication dictModifier dictMod.json

foamDictionary constant/neutroRegion/externalSource -entry isExternalSource -set false

GeN-Foam > log.GeN-Foam

#------------------------------------------------------------------------------
