#! /bin/sh

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

rm -f *.png

# Set simulation
runApplication -o foamDictionary 0/T -entry internalField -set "uniform 900" 
runApplication -a foamDictionary 0/T -entry boundaryField/cladOuter/temperatureSeries/values -set "((0 900) (50 1400) (100 900))" 
runApplication -a foamDictionary 0/T -entry boundaryField/cladOuter/value -set "uniform 900" 
runApplication -a foamDictionary system/controlDict -entry endTime -set "100" 
runApplication -a foamDictionary system/controlDict -entry deltaT -set "0.5" 

runApplication -o foamListTimes -rm 
rm -fr ./postProcessing
runApplication -o offbeat 
cp ./postProcessing/probes/0/betaFraction ./betaFraction
cp ./postProcessing/probes/0/T ./T

# Set BC for Q = 0
runApplication -o foamDictionary 0/T -entry internalField -set "uniform 900" 
runApplication -a foamDictionary 0/T -entry boundaryField/cladOuter/temperatureSeries/values -set "((0 900) (1e6 1400))" 
runApplication -a foamDictionary 0/T -entry boundaryField/cladOuter/value -set "uniform 900" 
runApplication -a foamDictionary system/controlDict -entry endTime -set "1e6" 
runApplication -a foamDictionary system/controlDict -entry deltaT -set "1e3" 

runApplication -o foamListTimes -rm 
rm -fr ./postProcessing
runApplication -o offbeat  
cp ./postProcessing/probes/0/betaFraction ./betaFractionEq
cp ./postProcessing/probes/0/T ./TEq

python3 extract_results.py

# rm T*
# rm betaFraction*