#!/bin/sh
# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh
runApplication -o changeDictionary
runApplication -o offbeat
#
runApplication -o postProcess -func sampleDict

CsSimulation=$(grep -i "Fraction of Cs release" log.offbeat | tail -n 1| cut -d" " -f5)
#
CsExpected=0.994653
#
echo "Released Cs fraction: $CsSimulation" >> results
echo "Codes range: [0.968, 0.996]" >> results
echo "Expected value: $CsExpected" >> results
#
relError=$(awk -v var1="$CsSimulation" \
                -v var2="$CsExpected" \
                'BEGIN {print (100*(var1-var2)/var2)}')


echo "Relative change: $relError%" >> results
