#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

cases="plateHole 
       beamBending 
       contact
       multiMaterial 
       thickCylinderExpansion 
       volumeConservationLargeStrain"

for case in $cases
do
    cd $case
    ./Allclean
    cd ..
done

rm -f results
