#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

python3 rodMaker.py rodDictALFRED

mv blockMeshDict system

runApplication blockMesh

runApplication dictModifier dictMod.json

touch FuelPin.foam

# currentFolder=$(basename $(pwd))
# if [ $currentFolder = "FuelPin9" ]
# then
runApplication $(getApplication)
# else
#     offbeat >/dev/null 2>&1
# fi

runApplication postProcess -func sampleDict

#------------------------------------------------------------------------------
