#!/bin/bash

cases="
gapVolume1Dsphere
hollowsphere_1D
sphere_1D
sphere_vhgr
testBuffer_alpha
testBuffer_creep
testBuffer_E_nu
testBuffer_k
testBuffer_swelling
testPyC_alpha
testPyC_alpha_spherical
testPyC_creep
testPyC_E_nu
testPyC_swelling
testSiC_creep
testSiC_k_Cp_E_alpha
testSwellingMatpro
"

for case in $cases; do
    cd $case
    ./Allclean
    cd ..
done

rm -f results
