#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory
set -o pipefail

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o fluentMeshToFoam contact.msh -scale 0.01 -writeZones
runApplication -o changeDictionary
runApplication -o foamListTimes -rm
rm -rf postProcessing results
STATUS=0

runApplication -o offbeat

python3 test.py | tee -a results

STATUS=$(expr $? "|" $STATUS)

echo "" | tee -a results

exit $STATUS

#------------------------------------------------------------------------------
