#!/bin/bash
# Author: Thomas Guilbaud, EPFL/Transmutex SA, 2022/05/25
# To be executed in rootCase

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions

duplicate() {
    if [ -d $2 ]; then
        echo "$2 exist"
        rm -r $2
    fi
    cp -r $1 $2
}

changeFolder() {
    # Update the polyMesh/ folder in a region. Use only after ideasUnvToFoam cmd
    # where polyMesh/ is generated by default in constant/
    region=$1
    if [ -d constant/$region/polyMesh ]; then
        cp -r constant/polyMesh constant/$region/
        rm -r constant/polyMesh
    else
        mv constant/polyMesh constant/$region/
    fi
}

# --- User Inputs
if [ $# -eq 1 ]; then
    pathToUNV=$1
    # --- If any UNV files, move them in the mesh/ folder
    mv "$pathToUNV"/*.unv mesh/
fi

# --- Duplicate the initial condition folder
duplicate 0.orig/ 0/

# --- Preprocessing
# Neutronic Region
ideasUnvToFoam mesh/Partition_wedgeNeutroRegion.unv
changeFolder neutroRegion
createPatch -overwrite -region neutroRegion

# Thermal-hydraulic Region
ideasUnvToFoam mesh/Partition_wedgeFluidRegion.unv
changeFolder fluidRegion
createPatch -overwrite -region fluidRegion
# The baffles seems to create errors and on "bounding" of k and epsilon
topoSet -region fluidRegion                     # Merge the baffle faces
createBaffles -overwrite -region fluidRegion
changeDictionary -region fluidRegion
# setFields -region fluidRegion

# Thermo-mechanical Region
blockMesh -region thermoMechanicalRegion
