#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Use a modified make
cp -r classes/thermalHydraulics/src/Make classes/thermalHydraulics/src/Make_backup
cp classes/thermalHydraulics/src/Make_FMU/files classes/thermalHydraulics/src/Make/
cp classes/thermalHydraulics/src/Make_FMU/options classes/thermalHydraulics/src/Make/

# clean
wclean libso ./classes/thermalHydraulics/src
wclean libso ./classes/thermalHydraulics/solvers
wclean


# Bring back the original make
cp classes/thermalHydraulics/src/Make_backup/files classes/thermalHydraulics/src/Make/
cp classes/thermalHydraulics/src/Make_backup/options classes/thermalHydraulics/src/Make/
rm -fr classes/thermalHydraulics/src/Make_backup

