#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Use a modified make
cp -r classes/thermalHydraulics/src/Make classes/thermalHydraulics/src/Make_backup
cp classes/thermalHydraulics/src/Make_FMU/files classes/thermalHydraulics/src/Make/
cp classes/thermalHydraulics/src/Make_FMU/options classes/thermalHydraulics/src/Make/

# Use a modified pump (necessary because pump is not runtime selectable)
cp -r classes/thermalHydraulics/src/phaseModels/structureModels/pump classes/thermalHydraulics/src/phaseModels/structureModels/pump_backup
cp classes/thermalHydraulics/src/phaseModels/structureModels/pump_FMU/pumpFMU.H classes/thermalHydraulics/src/phaseModels/structureModels/pump/pump.H
cp classes/thermalHydraulics/src/phaseModels/structureModels/pump_FMU/pumpFMU.C classes/thermalHydraulics/src/phaseModels/structureModels/pump/pump.C


# clean
wclean libso ./classes/thermalHydraulics/src
wclean libso ./classes/thermalHydraulics/solvers
wclean

# Bring back the original make
cp classes/thermalHydraulics/src/Make_backup/files classes/thermalHydraulics/src/Make/
cp classes/thermalHydraulics/src/Make_backup/options classes/thermalHydraulics/src/Make/
rm -fr classes/thermalHydraulics/src/Make_backup


# Bring back the original pump
cp classes/thermalHydraulics/src/phaseModels/structureModels/pump_backup/pump.H classes/thermalHydraulics/src/phaseModels/structureModels/pump/pump.H
cp classes/thermalHydraulics/src/phaseModels/structureModels/pump_backup/pump.C classes/thermalHydraulics/src/phaseModels/structureModels/pump/pump.C
rm -fr classes/thermalHydraulics/src/phaseModels/structureModels/pump_backup