#!/bin/sh

# This Allwmake will build the standard version of GeN-Foam
# A Beta version exists that can make use of FMUs,
# based on the FMU4FOAM library
# To compile that version, you will need to install
# FMU4FOAM, and modify 
# ./classes/thermalHydraulics/src/Make/options
# to include the externalComm library, and the path
# to /FMU4FOAM/ECI4FOAM/src/externalComm/lnInclude
#
# An example of options file is available in
# ./classes/thermalHydraulics/src/Make_exampleFMU/
# This file will work as is in case the FMU4FOAM 
# folder will be in the root of GeN-Foam/GeN-Foam


cd ${0%/*} || exit 1    # Run from this directory

clear

wmake $1 libso ./classes/thermalHydraulics/src
wmake $1 libso ./classes/thermalHydraulics/solvers
wmake $1 