#!/bin/sh
# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh
runApplication -o changeDictionary
runApplication -o offbeat
#
runApplication -o postProcess -func sampleDict

Dx_Simulation=$(cat postProcessing/sampleDict/10/outer/vectorField/D | sed -E 's/.*\(([^\s]+).*/\1/' | cut -d' ' -f1)

Dx_Expected=6.50359458925978E-07

#
echo "Displacement x: $Dx_Simulation" >> results
echo "Expected value: $Dx_Expected" >> results

relErrorX=`echo - | awk '{print 100*(var1-var2)/var2}' \
var1="$Dx_Simulation" var2="$Dx_Expected"`

echo "Relative error for Displacement x: $relErrorX%" >> results
