#!/bin/bash
set -o pipefail
STATUS=0

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

rm -f results
runApplication -o blockMesh 
runApplication -o changeDictionary 
runApplication -o offbeat

if [[ $WM_PROJECT_VERSION == *v* ]]
then	
	runApplication -o postProcess -func xyGraph_ESI
	gnuplot plots.gnuplot > log.gnuplot 
	python3 test_ESI.py | tee -a results
else
	runApplication -o postProcess -func xyGraph 
	gnuplot plots.gnuplot > log.gnuplot 
	python3 test.py | tee -a results
fi

STATUS=$(expr $? "|" $STATUS)

echo "" | tee -a results

exit $STATUS
